import type { Mode, Scene } from './types';

// The three conversation modes. `rate` feeds speechSynthesis (slower in Sanft).
export const MODES: Mode[] = [
  {
    id: 'sanft',
    label: 'Sanft',
    blurb: 'Langsam, geduldig, klares Hochdeutsch',
    rate: 0.9,
  },
  {
    id: 'echt',
    label: 'Echt',
    blurb: 'Normales Tempo, natürlich',
    rate: 1.0,
  },
  {
    id: 'schweiz',
    label: 'Schweiz',
    blurb: 'Schweizer Hochdeutsch, Grüezi & Merci vilmal',
    rate: 1.0,
  },
];

// The 20 built-in Swiss-life scenes. Learner-facing fields only — each scene's
// secret twist instruction lives server-side in lib/twists.ts, keyed by id.
export const SCENES: Scene[] = [
  {
    id: 'baeckerei',
    title: 'In der Bäckerei',
    emoji: '🥐',
    setting: 'Eine kleine Dorfbäckerei am Morgen',
    role: 'die Verkäuferin hinter der Theke',
    goal: 'Kaufe Brot und zwei Gipfeli und frage nach dem Preis.',
    level: 'A2',
  },
  {
    id: 'kita',
    title: 'In der Kita',
    emoji: '🧸',
    setting: 'Beim Abholen deines Kindes am Nachmittag',
    role: 'die Betreuerin der Kindergruppe',
    goal: 'Hole dein Kind ab und frage, wie der Tag war.',
    level: 'A2',
  },
  {
    id: 'sbb',
    title: 'Am SBB-Schalter',
    emoji: '🚆',
    setting: 'Der Billettschalter im Bahnhof',
    role: 'der Mitarbeiter am Schalter',
    goal: 'Kaufe ein Billett nach Bern für heute Nachmittag.',
    level: 'A2',
  },
  {
    id: 'handwerker',
    title: 'Der Handwerker',
    emoji: '🔧',
    setting: 'Ein Telefonanruf — bei dir tropft ein Wasserhahn',
    role: 'der Sanitär-Installateur am Telefon',
    goal: 'Erkläre das Problem und vereinbare einen Termin.',
    level: 'B1',
  },
  {
    id: 'arzt',
    title: 'In der Arztpraxis',
    emoji: '🩺',
    setting: 'Die Anmeldung beim Hausarzt',
    role: 'die medizinische Praxisassistentin',
    goal: 'Beschreibe deine Beschwerden und bekomme einen Termin.',
    level: 'B1',
  },
  {
    id: 'nachbar',
    title: 'Beim Nachbarn',
    emoji: '🏡',
    setting: 'Der Nachbar klingelt am Abend an der Tür',
    role: 'dein Nachbar aus dem Haus nebenan',
    goal: 'Führe ein freundliches Gespräch an der Tür.',
    level: 'A2',
  },
  {
    id: 'restaurant',
    title: 'Im Restaurant',
    emoji: '🍽️',
    setting: 'Ein Restaurant zum Mittagessen',
    role: 'der Kellner',
    goal: 'Bestelle ein Essen und frage nach den Zutaten (Allergie).',
    level: 'A2',
  },
  {
    id: 'migros',
    title: 'An der Migros-Kasse',
    emoji: '🛒',
    setting: 'Die Kasse im Supermarkt',
    role: 'die Kassiererin',
    goal: 'Bezahle deinen Einkauf und beantworte die Fragen an der Kasse.',
    level: 'A2',
  },
  {
    id: 'wohnung',
    title: 'Die Wohnungsbesichtigung',
    emoji: '🔑',
    setting: 'Besichtigung einer 3-Zimmer-Wohnung',
    role: 'die Verwalterin der Liegenschaft',
    goal: 'Stelle Fragen zur Wohnung und mache einen guten Eindruck.',
    level: 'B1',
  },
  {
    id: 'gemeinde',
    title: 'Auf der Gemeinde',
    emoji: '📋',
    setting: 'Die Einwohnerkontrolle — du meldest dich an',
    role: 'der Sachbearbeiter am Schalter',
    goal: 'Melde dich in der Gemeinde an.',
    level: 'B1',
  },
  {
    id: 'kundendienst',
    title: 'Der Kundendienst',
    emoji: '📞',
    setting: 'Ein Telefonanruf — dein Internet funktioniert nicht',
    role: 'die Mitarbeiterin im Kundendienst',
    goal: 'Melde die Störung und finde eine Lösung.',
    level: 'B1',
  },
  {
    id: 'elternabend',
    title: 'Beim Elterngespräch',
    emoji: '🎒',
    setting: 'Ein Gespräch mit der Lehrerin in der Schule',
    role: 'die Klassenlehrerin deines Kindes',
    goal: 'Sprich über die Fortschritte deines Kindes.',
    level: 'B1',
  },
  {
    id: 'apotheke',
    title: 'In der Apotheke',
    emoji: '💊',
    setting: 'Die Apotheke — du bist erkältet',
    role: 'der Apotheker',
    goal: 'Beschreibe deine Erkältung und bitte um ein Mittel.',
    level: 'A2',
  },
  {
    id: 'verein',
    title: 'Im Sportverein',
    emoji: '⚽',
    setting: 'Du willst einem Fussballverein beitreten',
    role: 'der Trainer des Vereins',
    goal: 'Frage, wie du Mitglied werden kannst.',
    level: 'A2',
  },
  {
    id: 'coiffeur',
    title: 'Beim Coiffeur',
    emoji: '✂️',
    setting: 'Der Coiffeursalon',
    role: 'die Coiffeuse',
    goal: 'Erkläre, wie du deine Haare geschnitten haben möchtest.',
    level: 'A2',
  },
  {
    id: 'post',
    title: 'Auf der Post',
    emoji: '📦',
    setting: 'Der Postschalter',
    role: 'der Mitarbeiter am Postschalter',
    goal: 'Verschicke ein Paket und frage nach den Optionen.',
    level: 'A2',
  },
  {
    id: 'garage',
    title: 'In der Autogarage',
    emoji: '🚗',
    setting: 'Die Garage — Zeit für den Reifenwechsel',
    role: 'der Automechaniker',
    goal: 'Bringe dein Auto zum Reifenwechsel.',
    level: 'B1',
  },
  {
    id: 'bibliothek',
    title: 'In der Bibliothek',
    emoji: '📚',
    setting: 'Die Gemeindebibliothek',
    role: 'die Bibliothekarin',
    goal: 'Melde dich für einen Ausweis an und frage nach Deutschkursen.',
    level: 'A2',
  },
  {
    id: 'markt',
    title: 'Auf dem Wochenmarkt',
    emoji: '🥕',
    setting: 'Ein Gemüsestand auf dem Markt',
    role: 'die Bäuerin am Stand',
    goal: 'Kaufe Gemüse und mach ein bisschen Smalltalk.',
    level: 'A2',
  },
  {
    id: 'panne',
    title: 'Die Autopanne',
    emoji: '🆘',
    setting: 'Ein Notruf — dein Auto ist am Strassenrand liegengeblieben',
    role: 'der Mitarbeiter der Pannenhilfe (TCS)',
    goal: 'Beschreibe die Panne und deinen Standort genau.',
    level: 'B1',
  },
];

export function getScene(id: string): Scene | undefined {
  return SCENES.find((s) => s.id === id);
}
