import type { Encounter } from "../../game/types";

export const boardPressure: Encounter = {
  id: "board-pressure",
  title: "The Break Room",
  difficulty: "adversarial",
  opponent: {
    name: "The Board Member",
    role: "A board member who corners you during the break in a board session",
    archetype: "Constrained Sponsor",
    blurb:
      "She pulled you aside with eight minutes before the session resumes. She is concerned about the Q3 miss. She can influence the decision, but she cannot make promises the CEO has not agreed to.",
  },
  scene:
    "The board session broke at 2:40 PM and she was waiting near the door. Eight minutes before the session resumes, the two of you are standing in the hallway outside the boardroom with no one else nearby. She is not hostile, but she came prepared.",
  objective:
    "Give a credible account of the Q3 miss without committing to numbers the CEO has not signed off on, and leave with her confidence intact.",
  startStanding: 40,
  startMomentum: 20,
  stages: [
    {
      id: "s1",
      prompt: "Walk me through what happened in Q3.",
      choices: [
        {
          id: "s1a",
          tag: "Own the number precisely",
          line: "We missed target by twelve percent. The driver was mid-market contraction that started in August and moved faster than our model assumed. I want to be clear about that gap before I say anything else.",
          points: 6,
          standing: 11,
          momentum: 15,
          reaction: "That is a clean answer. What did the model miss.",
          principle:
            "Owning the specific gap before anything else converts a potential interrogation into a working conversation. Precision signals that you command your own situation.",
          keywords: [
            "twelve percent",
            "missed target",
            "driver",
            "mid-market",
            "before anything else",
            "model",
            "precise",
            "own the number",
          ],
        },
        {
          id: "s1b",
          tag: "Acknowledge and lead with the lesson",
          line: "We missed, and the more important thing I want you to hear is what we learned: our mid-market signal was lagging by about six weeks, and we have fixed how we collect it.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "What was the actual miss. Give me the number first.",
          principle:
            "Leading with the lesson before the number is better than making excuses, but the specific gap should come first. She will ask for it anyway.",
          keywords: [
            "missed",
            "what we learned",
            "signal",
            "lagging",
            "fixed",
            "lesson",
            "acknowledge",
            "six weeks",
          ],
        },
        {
          id: "s1c",
          tag: "Explain how hard the quarter was",
          line: "It was a genuinely difficult quarter. Macro conditions tightened faster than anyone expected, and most of our peer companies came in short as well.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "I did not ask how hard the quarter was. I asked what happened.",
          principle:
            "Opening with external context before naming the miss reads as building an excuse. It tells a board member you are managing her perception before answering her question.",
          keywords: [
            "difficult quarter",
            "macro",
            "conditions tightened",
            "not alone",
            "peer companies",
            "genuinely hard",
            "context",
            "external",
          ],
        },
        {
          id: "s1d",
          tag: "Ask what she already knows",
          line: "Before I walk through it, can I ask what information you have already received? I want to make sure I am giving you the right level of detail.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "I am asking you. Walk me through it.",
          principle:
            "Asking a board member what she already knows before giving your account reads as calibrating your story to fit what she has heard. It signals that you are managing information, not sharing it.",
          keywords: [
            "what have you heard",
            "already received",
            "before I walk through",
            "right level",
            "what you know",
            "calibrate",
            "information you have",
            "check first",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "That is not the number. Give me the number first.",
        principle:
          "Under board-level scrutiny, vagueness reads as avoidance. Lead with the specific gap before you explain anything.",
      },
    },
    {
      id: "s2",
      prompt: "What is your confidence in Q4.",
      choices: [
        {
          id: "s2a",
          tag: "Give a range with named conditions",
          line: "I am confident in a range: we finish between eighty-eight and ninety-four of target. The lower end holds if enterprise deals slip past December fifteenth. The upper end requires two verbal commitments to sign. Those are the conditions I am watching closely.",
          points: 5,
          standing: 10,
          momentum: 14,
          reaction: "That is a range I can work with. What is the enterprise exposure specifically.",
          principle:
            "A range with named conditions is more credible than a point estimate, and it tells the board member exactly what signals to track. It also does not commit you to a number the CEO has not yet signed off on.",
          keywords: [
            "range",
            "lower end",
            "upper end",
            "conditions",
            "watching",
            "enterprise",
            "December fifteenth",
            "verbal commitments",
            "if then",
          ],
        },
        {
          id: "s2b",
          tag: "Name the floor you trust",
          line: "The number I am most confident in is that we will not miss the floor. Upside depends on two accounts I do not fully control. I would rather anchor you there than give you a number I cannot stand behind.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "What is the floor number.",
          principle:
            "Naming the number you can stand behind and flagging what you cannot is honest and practical. It gives the board member a stable reference point without overclaiming.",
          keywords: [
            "most confident",
            "floor",
            "upside",
            "two accounts",
            "anchor",
            "do not fully control",
            "stand behind",
            "trust",
          ],
        },
        {
          id: "s2c",
          tag: "Give a confident point estimate",
          line: "We are going to close Q4 at ninety-two percent of target. I feel good about where we are.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "That is a commitment. You know the CEO has not signed off on that number. Are you speaking for the company right now.",
          principle:
            "A confident point estimate without CEO sign-off creates a commitment you may not be able to honor. Board members hold specific numbers against you, and she will repeat this one.",
          keywords: [
            "ninety-two percent",
            "feel good",
            "going to close",
            "confident",
            "point estimate",
            "where we are",
            "committed number",
          ],
        },
        {
          id: "s2d",
          tag: "Say you are on track",
          line: "We are on track. The team is executing well and we have the pipeline to support the number.",
          points: -2,
          standing: -7,
          momentum: -3,
          reaction: "On track means nothing to me without a number. What is the number.",
          principle:
            "Saying you are on track without specifics is a non-answer in a board context. It reads as evasion and guarantees a harder follow-up.",
          keywords: [
            "on track",
            "executing well",
            "pipeline",
            "support the number",
            "team is",
            "vague assurance",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need a range or a number, not a feeling.",
        principle:
          "Board members cannot use feelings in a boardroom. Give a bounded range with the conditions that would move you inside or outside it.",
      },
    },
    {
      id: "s3",
      prompt:
        "I am going to ask you this directly. Do you think the team can hit the annual number.",
      choices: [
        {
          id: "s3a",
          tag: "Commit with conditions named",
          line: "I believe we can. Here is what has to go right: the two Q4 enterprise deals sign by the fifteenth, January pipeline accelerates from where it is today, and we hold our top three renewal accounts. I am watching all three weekly.",
          points: 6,
          standing: 11,
          momentum: 15,
          reaction: "That is a real answer. Which of the three are you least confident about.",
          principle:
            "Saying you believe you can hit the number and immediately naming the conditions is the only answer that is both honest and credible. It shows you have a working model of your own situation, not a talking point.",
          keywords: [
            "I believe we can",
            "what has to go right",
            "enterprise deals",
            "pipeline",
            "renewals",
            "conditions",
            "watching weekly",
            "three things",
          ],
        },
        {
          id: "s3b",
          tag: "Name the path honestly",
          line: "The path exists. I want to be honest that it requires specific things to happen that are not all in my control, and I would rather tell you that now than surprise you in January.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "What specifically needs to happen.",
          principle:
            "Naming the path without overclaiming signals a realistic model. It is more credible than a guarantee, and it gives her something to track without requiring CEO sign-off.",
          keywords: [
            "path exists",
            "honest",
            "specific things",
            "not all in my control",
            "surprise you",
            "January",
            "realistic",
          ],
        },
        {
          id: "s3c",
          tag: "Commit unconditionally",
          line: "Yes, absolutely. I would not be standing here if I did not believe we were going to hit it.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "Absolutely is not an answer, it is a posture. What conditions are you depending on.",
          principle:
            "An unconditional yes to a direct board question about hitting annual numbers reads as performance, not analysis. Board members will hold you to the word and not the conditions you chose not to name.",
          keywords: [
            "yes absolutely",
            "would not be here",
            "going to hit it",
            "unconditional",
            "posture",
            "committed",
          ],
        },
        {
          id: "s3d",
          tag: "Defer to the CEO",
          line: "I am not comfortable answering that without aligning with the CEO first. I want to make sure we are speaking with one voice.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "She did not ask for the company position. She asked what you think. That is a different question.",
          principle:
            "Deferring a direct question about your own judgment to the CEO reads as hiding behind process. Board members know the difference between a governance concern and someone who does not want to answer.",
          keywords: [
            "not comfortable",
            "aligning with CEO",
            "one voice",
            "sign-off",
            "company position",
            "defer",
            "governance",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I asked directly. I want a direct answer.",
        principle:
          "When a board member asks a direct question about your belief, give a direct answer with the conditions you are depending on. Anything else reads as evasion.",
      },
    },
    {
      id: "s4",
      prompt: "What do you need from me.",
      choices: [
        {
          id: "s4a",
          tag: "Name one thing within her role",
          line: "Stay calibrated on the range, not the point estimate. If the board starts treating the high end of the range as the commitment, I will be managing to the wrong target for the next sixty days. That is the one thing that would help most.",
          points: 6,
          standing: 11,
          momentum: 15,
          reaction: "I can do that. I will also keep this conversation between us unless the range changes materially.",
          principle:
            "Asking for something specific that is within a board member's actual role shows you understand how the relationship works. It also gives her a concrete way to help without overstepping either of your authority.",
          keywords: [
            "range",
            "point estimate",
            "board",
            "commitment",
            "sixty days",
            "target",
            "calibrated",
            "one thing",
            "within her role",
          ],
        },
        {
          id: "s4b",
          tag: "Offer a pre-session update",
          line: "Nothing right now. I will send you a brief update before the next session so you are not walking in cold. A paragraph, not a deck.",
          points: 3,
          standing: 6,
          momentum: 7,
          reaction: "I appreciate that. Before Thursday.",
          principle:
            "Offering a proactive update before the next board session is a low-cost, high-signal gesture. It keeps her informed without requiring her to ask, which is how trust builds in board relationships.",
          keywords: [
            "update",
            "next session",
            "paragraph",
            "not a deck",
            "proactive",
            "before Thursday",
            "keep informed",
            "walking in cold",
          ],
        },
        {
          id: "s4c",
          tag: "Ask her to advocate with other board members",
          line: "If you have confidence in the plan, it would mean a lot if you could help make the case to the other board members before the vote. You carry a lot of weight in that room.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "That is not how this works. I can influence things, but I cannot commit votes I do not have. You are asking me to exceed my role.",
          principle:
            "Asking a board member to lobby other board members puts her in an uncomfortable position and signals that you do not understand board governance. It makes the relationship transactional at exactly the wrong moment.",
          keywords: [
            "make the case",
            "other board members",
            "before the vote",
            "carry weight",
            "go to bat",
            "lobby",
            "advocate",
          ],
        },
        {
          id: "s4d",
          tag: "Say you have it covered",
          line: "Nothing, we have it. I appreciate you asking.",
          points: -2,
          standing: -6,
          momentum: -3,
          reaction: "That is a missed opportunity. I asked because I can help if you let me.",
          principle:
            "Declining a board member's offer of support closes a channel that is difficult to reopen. 'We have it' ends the conversation at exactly the moment you should be deepening the relationship.",
          keywords: [
            "nothing",
            "we have it",
            "covered",
            "appreciate you asking",
            "decline",
            "self-sufficient",
            "do not need",
            "we are fine",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "She offered to help. Use it or lose it.",
        principle:
          "When a board member asks what you need, name one thing within her actual role. The offer is rare, and letting it pass costs more than you think.",
      },
    },
  ],
  endings: [
    {
      id: "win",
      when: { momentumAtLeast: 68, standingAtLeast: 45 },
      result: "won",
      baseGrade: "A",
      resolution:
        "She checks her phone and says she has to get back in. Before she goes: 'I will stay focused on the range. Good conversation.' You walk back into the boardroom three minutes before the session resumes, with her confidence intact and a clear ask on the table.",
      lessons: [
        "Own the specific gap before anything else. Precision converts a board interrogation into a working conversation and signals that you command your own situation.",
        "A range with named conditions is more credible than a point estimate and does not require CEO sign-off you do not have. Bounding your confidence is accuracy, not weakness.",
        "When a board member asks what you need, name one thing within her actual role. It shows you understand how the relationship works and gives her a concrete way to help.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 50 },
      result: "partial",
      baseGrade: "C",
      resolution:
        "The break ends and you walk back in together. She does not look concerned, but she does not look confident either. You held the conversation without making promises you cannot keep, but you did not give her anything strong enough to carry into the boardroom.",
      lessons: [
        "Surviving a board hallway conversation without making promises is the floor, not the goal. The win is leaving her with something specific she can track.",
        "A range with conditions named is always more credible than a vague assurance. Even one named condition is better than none.",
        "Board relationships are built in the breaks, not the sessions. A proactive update offer costs almost nothing and compounds over time.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution:
        "She politely ends the conversation and walks back into the boardroom ahead of you. You either committed to a number the CEO has not signed off on, explained the quarter instead of owning it, or closed the channel when she offered to help. She is calibrated now, just not in the direction you needed.",
      lessons: [
        "Opening with external context before naming the miss reads as building an excuse. Board members hear this pattern immediately and it costs you the first thirty seconds.",
        "A confident point estimate without CEO sign-off creates a commitment the whole board will hold against you. Give a range, or give nothing you cannot stand behind.",
        "Asking a board member to lobby other board members puts her in an impossible position and signals you do not understand her role.",
      ],
    },
  ],
};
