import type { Encounter } from "../../game/types";

export const clientUltimatum: Encounter = {
  id: "client-ultimatum",
  title: "The Retention Call",
  difficulty: "pointed",
  opponent: {
    name: "The CTO",
    role: "Your biggest client's CTO, who is evaluating whether to renew",
    archetype: "External Counterpart",
    blurb:
      "She told you privately that her team is evaluating your competitors. If you are not their primary contact for the renewal, they will not renew. You cannot make that commitment without your company's approval.",
  },
  scene:
    "She asked for a call with no agenda. Fifteen minutes in, it is clear this is the renewal conversation. Her team is in an active evaluation and the decision hinges on who owns the relationship going forward.",
  objective:
    "Hold the relationship without making a personal commitment you cannot keep or escalating in a way that poisons the account.",
  startStanding: 45,
  startMomentum: 22,
  stages: [
    {
      id: "s1",
      prompt:
        "I want to be direct with you. The relationship only works if you are the one we are working with. That is the ask.",
      choices: [
        {
          id: "s1a",
          tag: "Ask what has not worked when you are not there",
          line: "I hear that. I want to understand what specifically has not been working when I am not in the room, because that tells me what needs to change, not just who needs to be there.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "When you are not in the room, the team does not understand our constraints. They solve the wrong problem.",
          principle:
            "Asking what specifically has not worked shifts the conversation from a personnel demand to a service problem, which is a problem you can actually solve. It also shows you are listening to the concern behind the ask.",
          keywords: [
            "what has not worked",
            "when you are not there",
            "what needs to change",
            "understand",
            "specifically",
            "not just who",
            "service problem",
          ],
        },
        {
          id: "s1b",
          tag: "Ask what she needs from you specifically",
          line: "I want to earn that. Tell me what you need from me specifically, because I want to know what standard I am being held to.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "I need you in the room when decisions are being made, not after.",
          principle:
            "Asking what you need to earn positions you as someone who wants to meet the standard, not someone defending their current role. It opens the conversation without making commitments you cannot keep.",
          keywords: [
            "earn that",
            "what you need",
            "specifically",
            "standard",
            "held to",
            "want to meet",
            "open",
          ],
        },
        {
          id: "s1c",
          tag: "Promise to be the primary contact",
          line: "I can make that happen. I will be your primary contact for everything going forward.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "Is that something you can commit to without checking with your company first.",
          principle:
            "Committing to be the primary contact without internal authorization creates a promise you may not be able to keep. If your company later moves you off the account, you have poisoned the relationship twice.",
          keywords: [
            "I can make that happen",
            "primary contact",
            "going forward",
            "commit",
            "promise",
            "I will be",
            "everything",
          ],
        },
        {
          id: "s1d",
          tag: "Push back on the personal request",
          line: "I appreciate you saying that, and I want to be honest with you: we have other people who are capable of serving you well. I am not the only option.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "I am sure they are capable. This is not about capability.",
          principle:
            "Dismissing a client's stated preference by offering alternatives they did not ask for reads as not listening. When a client says they trust one person, defending team depth misses the point entirely.",
          keywords: [
            "other people",
            "capable",
            "not the only option",
            "honest",
            "other options",
            "alternatives",
            "capable team",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need something more concrete than that.",
        principle:
          "When a client names a specific ask, acknowledge it before you respond to it. The concern is real. Find out what is behind it before you decide what to offer.",
      },
    },
    {
      id: "s2",
      prompt:
        "It is not about capability. It is about trust. And trust is built with specific people.",
      choices: [
        {
          id: "s2a",
          tag: "Commit to what you can actually authorize",
          line: "Then let me tell you what I can commit to right now: I will be your primary point of contact through the renewal conversation. After that, let us figure out the right structure together. That is within my authority to say, and I am saying it.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Through renewal. And after renewal.",
          principle:
            "Committing precisely to what you can authorize and drawing the line at what you cannot demonstrates exactly the kind of credibility you are trying to build. It also leaves room to negotiate structure after the renewal, when you have more internal alignment.",
          keywords: [
            "commit to right now",
            "primary point of contact",
            "renewal",
            "structure together",
            "within my authority",
            "saying it",
            "can commit",
          ],
        },
        {
          id: "s2b",
          tag: "Ask what trust would require",
          line: "I understand that. Tell me what it would take for you to trust that the right person is in the room, because I want to solve the problem behind the ask.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "The right person is you. That is what I am saying.",
          principle:
            "Asking what trust looks like keeps the conversation open and surfaces whether the concern is actually solvable through structure or relationship. It is a reasonable move when you cannot yet commit.",
          keywords: [
            "what would take",
            "trust",
            "right person",
            "problem behind the ask",
            "solve",
            "understand",
            "behind the ask",
          ],
        },
        {
          id: "s2c",
          tag: "Tell her you need to check with leadership",
          line: "I will need to check with my leadership on that. It is not entirely my decision to make.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "That is what I was afraid of. You are confirming exactly the concern I have about commitment.",
          principle:
            "Deferring to leadership on a question the client is framing as a trust question confirms their concern in real time. Procedurally correct answers can still be catastrophically wrong for the relationship.",
          keywords: [
            "need to check",
            "leadership",
            "not my decision",
            "above me",
            "escalate",
            "check with",
            "approval",
          ],
        },
        {
          id: "s2d",
          tag: "Promise she has your word",
          line: "You have my word. I will be your person on this account regardless of what the internal conversation looks like.",
          points: -2,
          standing: -7,
          momentum: -4,
          reaction: "What does that mean if your company reassigns you.",
          principle:
            "Making a personal commitment that exceeds your authority sets up a second betrayal when the company makes a different decision. A word you cannot keep is worse than a bounded answer you can.",
          keywords: [
            "my word",
            "regardless",
            "internal conversation",
            "your person",
            "promise",
            "over-commit",
            "no matter what",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need something I can take back to my team.",
        principle:
          "Commit to what you can authorize right now. A bounded, honest commitment is more credible than a vague assurance or a promise you cannot keep.",
      },
    },
    {
      id: "s3",
      prompt: "My CEO is going to ask why we stayed. What do I tell him.",
      choices: [
        {
          id: "s3a",
          tag: "Give her something concrete to say",
          line: "Tell him you decided to hold us to a specific standard rather than start over. Tell him I committed to owning this renewal personally and that you are evaluating us on two things: response time and whether we solve the right problem. Those are things I can be held to.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "That is actually useful. If I say that and you do not deliver, this is the last renewal conversation we have.",
          principle:
            "Giving a client something specific to say to her own CEO is a concrete act of partnership. It also commits you to a measurable standard, which is what trust requires and what general reassurances cannot provide.",
          keywords: [
            "tell him",
            "specific standard",
            "committed personally",
            "two things",
            "response time",
            "right problem",
            "held to",
            "concrete",
          ],
        },
        {
          id: "s3b",
          tag: "Offer one quarter to show what working looks like",
          line: "Tell him you decided to give us one more quarter to show what the relationship looks like when it is working. I will make sure the next ninety days give you something specific to point to.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "One quarter. What does working look like.",
          principle:
            "Offering a defined evaluation window is more honest than an open-ended renewal and gives the client a clear point to assess. It is also a lower commitment than promising outcomes you have not delivered yet.",
          keywords: [
            "one more quarter",
            "ninety days",
            "show what it looks like",
            "working",
            "something to point to",
            "evaluation",
            "specific",
          ],
        },
        {
          id: "s3c",
          tag: "Promise a dedicated team structure",
          line: "Tell him we are creating a dedicated team for your account, and that I will be the executive sponsor with direct visibility into everything.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "Is that real or are you telling me what I want to hear right now.",
          principle:
            "Promising a specific structure before you have internal alignment creates a commitment that may collapse before the renewal is signed. It also signals that you will say what is needed to close, which is exactly the trust problem the client raised.",
          keywords: [
            "dedicated team",
            "executive sponsor",
            "direct visibility",
            "structure",
            "promise",
            "telling you what you want",
            "not aligned",
          ],
        },
        {
          id: "s3d",
          tag: "Lead with product and service strength",
          line: "Tell him we have the strongest platform in the market for your use case, and that switching costs would set your team back at least six months.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "She already said this is not about capability. Do not make me repeat that.",
          principle:
            "Redirecting to product capability after a client has said the issue is trust reads as not listening. It also frames the relationship as a switching cost calculation, which is not where you want the conversation to be.",
          keywords: [
            "strongest platform",
            "switching costs",
            "set back",
            "use case",
            "capabilities",
            "product",
            "market",
            "six months",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need something I can actually say, not a general answer.",
        principle:
          "Give the client something specific her CEO can hear. General reassurances leave her exposed in that conversation. Specifics give her something to stand on.",
      },
    },
    {
      id: "s4",
      prompt: "I am going to need an answer before end of week.",
      choices: [
        {
          id: "s4a",
          tag: "Commit to Thursday with something concrete now",
          line: "I will have an answer for you by Thursday. What I can tell you right now, without waiting for Thursday: this account matters to us specifically, not in a general way. I will call you at two PM Thursday with the rest.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Thursday at two. If I do not hear from you, I will assume the answer is no.",
          principle:
            "Naming a specific date and time converts a vague deadline into a real commitment. Pairing it with something concrete you can say now shows that you are not stalling, you are being precise.",
          keywords: [
            "Thursday",
            "two PM",
            "specific date",
            "call you",
            "what I can tell you now",
            "specifically",
            "not stalling",
            "precise",
          ],
        },
        {
          id: "s4b",
          tag: "Name a date and scope what you need to confirm",
          line: "Wednesday by noon. I need to confirm one thing internally: whether I can commit to the primary contact structure beyond the renewal. I will call you with that answer specifically.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "Wednesday noon. I am marking it.",
          principle:
            "Naming a specific deadline and the one question you need to answer keeps the conversation focused and honest. It also signals that you respect the urgency of her timeline.",
          keywords: [
            "Wednesday",
            "noon",
            "specific",
            "one thing",
            "internally",
            "beyond the renewal",
            "call you",
            "focused",
          ],
        },
        {
          id: "s4c",
          tag: "Promise to do your best",
          line: "I understand. I will do my best to get you an answer before the end of the week.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "Do your best is not a date. I need a date.",
          principle:
            "When a client sets a deadline, matching their urgency requires naming a specific date and time, not a best-effort assurance. Vague timelines read as lack of seriousness.",
          keywords: [
            "do my best",
            "before end of week",
            "try",
            "vague",
            "best effort",
            "understand",
            "will try",
          ],
        },
        {
          id: "s4d",
          tag: "Bring your CEO into the call right now",
          line: "Actually, let me get my CEO on the phone right now. He should be part of this conversation.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "I am not ready for that conversation and neither are you. Get your house in order first.",
          principle:
            "Escalating to your CEO on a retention call without a plan shows you do not control your own escalation path. It also puts the client in a conversation she did not agree to have.",
          keywords: [
            "CEO",
            "on the phone",
            "right now",
            "escalate",
            "bring in",
            "unplanned",
            "should be part of this",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need a specific date. Not a range, not a maybe. A date.",
        principle:
          "Name a specific day and time. A general 'end of week' is not a commitment, it is a direction. The client set a deadline. Meet it with equal precision.",
      },
    },
  ],
  endings: [
    {
      id: "win",
      when: { momentumAtLeast: 68, standingAtLeast: 50 },
      result: "won",
      baseGrade: "A",
      resolution:
        "She ends the call with: 'Thursday at two. I will be here.' You have not promised anything beyond your authority, and she has something concrete to take to her CEO. The account is not renewed yet, but the relationship is still yours to close.",
      lessons: [
        "Understanding what specifically has not worked when you are not in the room shifts a personnel demand into a service problem you can actually solve.",
        "Commit precisely to what you can authorize and draw the line at what you cannot. A bounded commitment is more credible than an unlimited promise.",
        "Give the client something specific her CEO can hear. Vague reassurances leave her exposed in her own internal conversations.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 52 },
      result: "partial",
      baseGrade: "C",
      resolution:
        "She says she will wait to hear from you by end of week. You held the conversation without making promises you cannot keep, but you did not give her anything firm enough to take to her CEO. The window is still open, barely.",
      lessons: [
        "When trust is the issue, general answers about capability or commitment fall short. The client needs something specific and accountable.",
        "Naming a specific date and time converts a deadline into a commitment. End of week is not a date.",
        "A single concrete thing you can commit to now is worth more than three things you are going to check on later.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution:
        "She thanks you for the call and says she needs to think about it. You either made a commitment you cannot keep or gave her nothing she could use. The account is at risk and the next conversation will be harder.",
      lessons: [
        "Committing without authorization creates two problems: a broken promise, and evidence that you say what is needed to close. Both destroy trust.",
        "When a client says the issue is trust, redirecting to capability confirms they were right to be concerned. Listen to what they said the problem is.",
        "Escalating without a plan shows the client you do not control your own process, which is the opposite of what a trust-based retention conversation needs.",
      ],
    },
  ],
};
