import type { Encounter } from "../../game/types";

export const governanceCharter: Encounter = {
  id: "governance-charter",
  title: "The Charter",
  opponent: {
    name: "The Counterpart",
    role: "A peer fighting you over ownership of a domain",
    archetype: "Territorial Counterpart",
    blurb: "Turn an ownership fight into a written charter that protects you both.",
  },
  difficulty: "pointed",
  scene: "You and a peer keep colliding over who owns a domain. You want to turn the recurring fight into a formal written charter.",
  objective: "Convert the ownership fight into a clear written charter with defined decision rights.",
  startStanding: 38,
  startMomentum: 18,
  stages: [
    {
      id: "s1-opening",
      prompt: "He crosses his arms. \"We keep stepping on each other and I am tired of it. So let us be clear. This domain is mine.\"",
      choices: [
        {
          id: "s1-grab",
          tag: "Claim the whole domain",
          line: "Actually it is mine, and it always has been. You have been operating in my territory and it needs to stop.",
          points: -3,
          standing: -16,
          momentum: -5,
          reaction: "So we are doing this. Two people claiming the same flag is exactly why nothing gets decided. I am not backing down.",
          principle: "Meeting a territory claim with a counterclaim guarantees a standoff that neither side can finish.",
          keywords: ["land grab", "claim everything", "territory", "counterclaim", "standoff", "ego"],
        },
        {
          id: "s1-write",
          tag: "Propose writing it down",
          line: "I do not want to fight you over a flag. I want to write down who decides what, once, so we stop relitigating it every week.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Writing it down. Honestly that is more than the last person tried. Alright, I am listening.",
          principle: "Move a recurring fight onto paper, because a written agreement ends the weekly relitigation.",
          keywords: ["write it down", "document", "charter", "stop relitigating", "clarity", "agreement"],
        },
        {
          id: "s1-acknowledge",
          tag: "Acknowledge the collision cost",
          line: "We are both losing time on this, and so is the team watching us collide. Can we agree the cost of the fight is the real problem?",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "I will give you that. The collisions are costing both of us. So what do you actually propose?",
          principle: "Naming the shared cost of conflict creates common ground before you negotiate the substance.",
          keywords: ["shared cost", "collision", "common ground", "team impact", "acknowledge", "align"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Go on. But I am not giving up ground for nothing.",
        principle: "Turn a turf claim into a problem you both own before you reach for who owns what.",
      },
    },
    {
      id: "s2-rights",
      prompt: "He leans forward. \"Fine, a document. But if you think this is about you carving up my work, we are done before we start.\"",
      choices: [
        {
          id: "s2-rights",
          tag: "Define decision rights, not territory",
          line: "It is not about carving up work. It is about who decides what. Let us write down who is accountable, who is consulted, and who just needs to be informed.",
          points: 6,
          standing: 11,
          momentum: 16,
          reaction: "Decision rights instead of borders. Yes. That is the part that actually keeps blowing up, so let us name it.",
          principle: "Define decision rights rather than territory, because most turf fights are really about who decides.",
          keywords: ["decision rights", "accountable", "consulted", "informed", "not territory", "roles"],
        },
        {
          id: "s2-borders",
          tag: "Draw hard borders",
          line: "Simple. Everything on this side of the line is yours, everything on that side is mine, and we never cross. Clean borders, no overlap.",
          points: -2,
          standing: -11,
          momentum: -4,
          reaction: "Borders sound clean until the work does not respect them, which it never does. Then we are right back here.",
          principle: "Hard borders fail because real work crosses lines, so the conflict returns at every seam.",
          keywords: ["hard borders", "divide territory", "split", "rigid", "overlap fails", "seams"],
        },
        {
          id: "s2-overlap",
          tag: "Name the overlap explicitly",
          line: "Most of this is clearly yours or clearly mine. Let us spend our time on the narrow band where we actually overlap and write a rule just for that.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "That is sensible. Ninety percent is obvious. Let us solve the part that is not.",
          principle: "Focus the agreement on the contested seam, since the clear areas were never the problem.",
          keywords: ["overlap", "contested seam", "narrow band", "focus", "specific rule", "edge cases"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Keep going. As long as this is not a takeover dressed up as a process.",
        principle: "Decide who decides, and most ownership disputes quietly dissolve.",
      },
    },
    {
      id: "s3-win",
      prompt: "He softens but stays wary. \"And what do I actually get out of this? I am not signing something that makes me look like the junior partner.\"",
      choices: [
        {
          id: "s3-give",
          tag: "Give him a clear win area",
          line: "You should own the strategy calls here outright. That is your strength and it should be unambiguously yours in the charter. I will own delivery.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Now we are talking. If the strategy lane is clearly mine, written down, I can stand behind this.",
          principle: "Hand the other side a clear, named win so the charter feels like a settlement, not a defeat.",
          keywords: ["clear win", "give ownership", "named lane", "strength", "settlement", "mutual"],
        },
        {
          id: "s3-take",
          tag: "Keep the good parts for yourself",
          line: "You can have the operational maintenance side. The strategy and the roadmap, naturally, stay with me where they belong.",
          points: -3,
          standing: -15,
          momentum: -5,
          reaction: "So I get the chores and you get the crown. No. That is the same takeover with nicer wording.",
          principle: "Keeping every valuable lane for yourself turns a charter into a takeover the other side will reject.",
          keywords: ["take the good parts", "self serving", "chores for them", "imbalanced", "takeover", "greedy"],
        },
        {
          id: "s3-trade",
          tag: "Trade lanes by strength",
          line: "Let us assign each lane to whoever is genuinely stronger at it, not by who shouts loudest. I think that gives you a couple of clear ones.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Assigning by who is actually better at it I can defend to my team. Let us map it that way.",
          principle: "Allocate ownership by genuine strength so the split is defensible to both teams.",
          keywords: ["trade by strength", "merit", "fair split", "defensible", "assign lanes", "balanced"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Show me what is in this for me and I will keep going.",
        principle: "A durable agreement gives the other party a win they can say out loud to their own team.",
      },
    },
    {
      id: "s4-close",
      prompt: "He nods slowly. \"Okay. This could work. How do we lock it so it is not just another conversation we forget?\"",
      choices: [
        {
          id: "s4-escalate",
          tag: "Drag leadership in to rule",
          line: "Let us just take the whole thing to our boss and have her decide who owns what. Whatever she rules, we live with.",
          points: -2,
          standing: -12,
          momentum: -4,
          reaction: "Run upstairs to settle our own fight? That makes us both look like we cannot operate as peers. Hard pass.",
          principle: "Escalating a peer dispute upward signals you cannot self-govern and weakens both of you.",
          keywords: ["escalate", "drag boss in", "ask leadership", "cannot self govern", "weak", "upstairs"],
        },
        {
          id: "s4-sign",
          tag: "Write, sign, and set a review date",
          line: "We write it today, we both sign it, and we put a review date on it for ninety days. It is binding until then, and we revisit with data, not emotion.",
          points: 6,
          standing: 11,
          momentum: 17,
          reaction: "Sign it and revisit in ninety days with data. That is exactly clean enough that I trust it. Let us draft it now.",
          principle: "Lock a charter with a signature and a review date so it is binding yet open to revision.",
          keywords: ["sign", "review date", "binding", "revisit with data", "lock it", "durable"],
        },
        {
          id: "s4-handshake",
          tag: "Keep it informal and vague",
          line: "Honestly we do not need anything formal. We understand each other now. A handshake between us is enough.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "A handshake is what we have had this whole time, and look where it got us. If it is not written, it is not real.",
          principle: "Leaving the agreement informal recreates the exact ambiguity that caused the fight.",
          keywords: ["handshake", "informal", "vague", "no document", "verbal only", "ambiguity"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Tell me how we make this stick.",
        principle: "An agreement only holds when it is written, signed, and given a date to be revisited.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 38 },
      result: "won",
      baseGrade: "A",
      resolution: "You turned a weekly turf fight into a signed charter built on decision rights instead of borders. He owns a lane he can defend to his team, you own yours, and the contested seam now has a written rule with a ninety-day review attached. Two peers walked in colliding and walked out self-governing, with the kind of document that ends arguments instead of starting them.",
      lessons: [
        "Move a recurring fight onto paper, because a written, signed charter ends the weekly relitigation.",
        "Define decision rights, not territory, since most turf battles are really about who decides.",
        "Give the other side a clear, named win so the agreement reads as a settlement rather than a defeat.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You got him talking and reached a rough understanding, but you left it softer than it needed to be, leaning on hard borders or a handshake. The immediate heat is down, yet the seam where you actually collide is still loosely defined. You bought some peace, though not the durable charter that would have stopped the next collision cold.",
      lessons: [
        "Hard borders and handshakes both fail because real work crosses lines and memories fade.",
        "Solve the contested seam explicitly, because the clear areas were never the problem.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "Either you met his claim with a counterclaim, tried to keep every valuable lane for yourself, or reached for the boss to settle it. He read all of it as a takeover or a sign you could not operate as a peer, and dug in. The fight is exactly where it started, except now there is less trust to work with next time.",
      lessons: [
        "Meeting a territory claim with a counterclaim guarantees a standoff neither side can finish.",
        "Keeping every valuable lane for yourself turns a charter into a takeover the other side rejects.",
        "Escalating a peer dispute upward signals you cannot self-govern and weakens you both.",
      ],
    },
  ],
};
