import type { Encounter } from "../../game/types";

export const hardFeedback: Encounter = {
  id: "hard-feedback",
  title: "The Hard Feedback",
  opponent: {
    name: "The Sponsor",
    role: "A senior sponsor delivering blunt feedback",
    archetype: "Constrained Sponsor",
    blurb: "He is giving you hard feedback. Take it well and turn it into a sponsorship ask.",
  },
  difficulty: "measured",
  scene: "A senior sponsor delivers blunt critical feedback about you. You must receive it well and convert the moment into a sponsorship ask.",
  objective: "Absorb the feedback credibly and convert the goodwill into a concrete sponsorship action.",
  startStanding: 55,
  startMomentum: 20,
  stages: [
    {
      id: "s1-opening",
      prompt: "He does not soften it. \"I will be direct. People find you sharp in the room. You win the point and lose the people. That is holding you back.\"",
      choices: [
        {
          id: "s1-defensive",
          tag: "Get defensive",
          line: "I think that is unfair. I push hard because I care about the work, and if people read that as sharp, that is on them.",
          points: -3,
          standing: -14,
          momentum: -5,
          reaction: "And that right there is the reaction that proves my point. I gave you something real and you handed it back.",
          principle: "Defending against feedback in the moment confirms the very problem the feedback names.",
          keywords: ["defensive", "deflect", "blame others", "reject feedback", "unfair", "pushback"],
        },
        {
          id: "s1-reflect",
          tag: "Thank him and reflect it back",
          line: "Thank you, that is hard to hear and useful. So I am winning the argument and losing the room, and that is costing me influence. Have I got that right?",
          points: 6,
          standing: 9,
          momentum: 15,
          reaction: "Exactly right. And the fact that you can hear it and say it back cleanly tells me you can actually fix it.",
          principle: "Reflecting feedback back accurately proves you received it and turns the giver into an ally.",
          keywords: ["thank you", "reflect back", "accurate", "receive well", "listen", "summarize"],
        },
        {
          id: "s1-overapologize",
          tag: "Over-apologize and shrink",
          line: "You are completely right, I am so sorry. I clearly have no idea how I come across and I feel awful about it.",
          points: 1,
          standing: -3,
          momentum: 3,
          reaction: "Easy. I am not trying to make you feel terrible. I need you steadier than that, not flattened.",
          principle: "Collapsing into apology shifts the burden onto the giver and reads as fragility, not growth.",
          keywords: ["over apologize", "shrink", "self flagellate", "fragile", "guilt", "collapse"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Let us see if you can actually take this on board.",
        principle: "How you receive hard feedback is itself the first test of whether you can act on it.",
      },
    },
    {
      id: "s2-specifics",
      prompt: "He continues. \"Last week in the review, you cut three people off mid-sentence. You were right each time. It did not matter.\"",
      choices: [
        {
          id: "s2-argue",
          tag: "Argue the feedback is wrong",
          line: "I remember that meeting differently. We were behind, I kept us on track, and frankly someone had to. I would do it again.",
          points: -3,
          standing: -15,
          momentum: -5,
          reaction: "Then we are wasting each other's time. I am describing the effect you have, and you are arguing about the footage.",
          principle: "Disputing the specifics of feedback signals you value being right over being effective.",
          keywords: ["argue", "dispute facts", "i was right", "rationalize", "justify", "resist"],
        },
        {
          id: "s2-own",
          tag: "Own the specific behavior",
          line: "I do remember cutting them off, and you are right that being correct did not buy back the cost. I own that pattern.",
          points: 6,
          standing: 9,
          momentum: 15,
          reaction: "Good. Naming the exact behavior without a but attached is most of the work right there.",
          principle: "Owning the specific behavior without a qualifier is what makes an apology credible.",
          keywords: ["own it", "specific behavior", "no but", "accountable", "honest", "name it"],
        },
        {
          id: "s2-ask",
          tag: "Ask for the pattern",
          line: "Help me see the pattern. When does this show up most, so I am watching for the right trigger and not just the one meeting?",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Smart question. It is worst when you are under time pressure and certain you are right. Watch for that combination.",
          principle: "Asking for the pattern behind an example turns a single critique into something you can actually change.",
          keywords: ["ask pattern", "trigger", "curiosity", "understand", "actionable", "probe"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "I am watching how you handle the detail, not just the headline.",
        principle: "Stay with the specifics, because that is where feedback becomes something you can fix.",
      },
    },
    {
      id: "s3-commit",
      prompt: "He eases slightly. \"Look, I would not bother saying any of this if I did not think you were worth it. So what are you going to do?\"",
      choices: [
        {
          id: "s3-vague",
          tag: "Promise to be better vaguely",
          line: "I hear you. I will work on it and try to be more aware of how I come across going forward.",
          points: 1,
          standing: -2,
          momentum: 3,
          reaction: "Try to be more aware is what everyone says before nothing changes. Give me something I can actually check.",
          principle: "A vague promise to improve is indistinguishable from no commitment at all.",
          keywords: ["vague", "try harder", "be aware", "no specifics", "generic", "soft"],
        },
        {
          id: "s3-concrete",
          tag: "Commit to one concrete change",
          line: "Here is my commitment. In the next three reviews, I let everyone finish before I respond, and I will ask you to call me out live if I slip. One behavior, measurable.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Now that I can hold you to. One behavior, three meetings, and I get to flag it. That is a real plan.",
          principle: "Convert feedback into one concrete, measurable change with a built-in check, not a broad intention.",
          keywords: ["concrete", "one change", "measurable", "specific commitment", "checkable", "plan"],
        },
        {
          id: "s3-overhaul",
          tag: "Promise a total transformation",
          line: "I am going to overhaul how I operate completely. New approach to meetings, communication, all of it. You will see a different person.",
          points: 2,
          standing: 2,
          momentum: 5,
          reaction: "I do not need a different person. I need this one to stop cutting people off. Do not boil the ocean.",
          principle: "Promising a total transformation is less believable than committing to one change you will keep.",
          keywords: ["overhaul", "transform everything", "grand promise", "overreach", "unrealistic", "all of it"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Tell me the one thing you will actually do.",
        principle: "One specific change you keep beats a sweeping promise you cannot.",
      },
    },
    {
      id: "s4-sponsor",
      prompt: "He stands to leave, satisfied. \"Good conversation. You took that better than most. Anything else before I go?\"",
      choices: [
        {
          id: "s4-nothing",
          tag: "Thank him and leave it there",
          line: "No, that is everything. Thank you again for being straight with me. I will get to work on it.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Good man. Go make it happen.",
          principle: "Closing politely is safe, but it leaves the goodwill you just earned unconverted.",
          keywords: ["thank you", "leave it", "polite close", "no ask", "safe", "passive"],
        },
        {
          id: "s4-ask",
          tag: "Ask him to sponsor the growth",
          line: "Actually, yes. You clearly see how I operate at this level. Once you see this change land, would you put me forward for the cross-team lead role? Your word there would carry it.",
          points: 6,
          standing: 10,
          momentum: 17,
          reaction: "Tell you what. Show me the change over the next month and I will put your name on that list myself.",
          principle: "Convert the trust earned by receiving feedback well into a specific, conditional sponsorship ask.",
          keywords: ["sponsorship ask", "put me forward", "specific role", "conditional", "convert goodwill", "advocate"],
        },
        {
          id: "s4-grab",
          tag: "Make a demanding ask",
          line: "Since we are being honest, I think I am overdue for a promotion and I would like you to push for it now.",
          points: -3,
          standing: -13,
          momentum: -5,
          reaction: "We just talked about a problem and your takeaway is to ask me to promote you today? Read the room.",
          principle: "Turning a feedback moment into an immediate demand misreads the room and spends trust you just built.",
          keywords: ["demand", "promote me now", "entitled", "premature", "misread", "grab"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "If there is an ask, make it a clean one.",
        principle: "The moment after you receive feedback well is the strongest time to ask for sponsorship, if the ask is earned and specific.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 55 },
      result: "won",
      baseGrade: "A",
      resolution: "You took the blunt feedback without flinching, reflected it back accurately, and committed to one concrete change he could check. Then, with the trust freshly earned, you converted the moment into a specific sponsorship ask tied to that very growth. He left ready to put your name forward himself. You did not just survive hard feedback, you turned it into a sponsor's commitment.",
      lessons: [
        "Reflect hard feedback back accurately, because how you receive it is the first proof you can act on it.",
        "Convert feedback into one concrete, measurable change with a built-in check, not a broad intention.",
        "The moment after you receive feedback well is the strongest time to ask for sponsorship, if the ask is specific and earned.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You handled the feedback reasonably and kept his respect, but you stayed safe at the close or let your commitment drift toward the vague. He leaves with a decent impression and no concrete reason to act on your behalf. You protected the relationship without converting the rare goodwill of the moment into anything you can bank.",
      lessons: [
        "A vague promise to improve is hard to tell apart from no commitment at all.",
        "Receiving feedback well earns trust, but trust unconverted into a specific ask simply fades.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "You got defensive, argued the specifics, or turned the moment into a demand. Each move confirmed the very thing he was trying to help you with, and the goodwill that brought him to give you honest feedback drained away. He will think twice before spending candor on you again, and the sponsorship that was within reach is gone.",
      lessons: [
        "Defending against feedback in the moment confirms the exact problem it names.",
        "Disputing the specifics signals you value being right over being effective.",
        "Turning a feedback moment into an immediate demand misreads the room and spends trust you just built.",
      ],
    },
  ],
};
