import type { Encounter } from "../../game/types";

export const offerCounter: Encounter = {
  id: "offer-counter",
  title: "The Counteroffer",
  opponent: {
    name: "The Counterpart",
    role: "An internal decision partner you negotiate the VP move with",
    archetype: "External Counterpart",
    blurb: "You hold an outside offer. Use it to accelerate the VP move without burning trust.",
  },
  difficulty: "pointed",
  scene: "You hold a real external offer. You meet an internal decision partner to accelerate your VP move. You must use the offer as information, not a threat.",
  objective: "Accelerate the VP timeline using the offer as a signal of market value, without issuing an ultimatum.",
  startStanding: 50,
  startMomentum: 25,
  stages: [
    {
      id: "s1-opening",
      prompt: "She closes the door and sits. \"I heard you have something outside. Before this turns into a negotiation, tell me what we are actually doing here.\"",
      choices: [
        {
          id: "s1-context",
          tag: "Offer as context, prefer to stay",
          line: "I want to be straight with you. I have an offer, but I am here because I would rather build the next chapter here. I am sharing it as context, not as a lever.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "I appreciate you opening with that. It changes the tone. So this is a conversation, not a hostage situation.",
          principle: "Lead by stating your preference to stay so the offer reads as information rather than a threat.",
          keywords: ["context", "prefer to stay", "transparency", "not a lever", "honest", "intent"],
        },
        {
          id: "s1-ultimatum",
          tag: "Issue an ultimatum",
          line: "Here is the situation. Match the title and the package by the end of the week or I am gone. That is the deal.",
          points: -3,
          standing: -16,
          momentum: -5,
          reaction: "So that is where we are. You should know that people who put a gun on the table rarely like how the room responds.",
          principle: "An ultimatum converts a value conversation into a power test you are likely to lose internally.",
          keywords: ["ultimatum", "match or leave", "deadline threat", "demand", "pressure", "coercion"],
        },
        {
          id: "s1-frame",
          tag: "Frame it as timing, not money",
          line: "The offer mostly tells me the market is moving faster than our timeline. I want to talk about whether we can move faster too.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "That is a fair read. Timing I can engage with. Let us talk about what faster looks like.",
          principle: "Reframe an offer as a signal about timing so the discussion stays about the path, not the number.",
          keywords: ["timing", "market signal", "pace", "faster timeline", "reframe", "path"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Alright. Let us see where you are going with this.",
        principle: "Set the frame before you reveal the offer, because the frame decides how it lands.",
      },
    },
    {
      id: "s2-number",
      prompt: "She leans in. \"So what is the number? Give me something concrete I can take upstairs.\"",
      choices: [
        {
          id: "s2-honest",
          tag: "Be precise and honest",
          line: "I will give you the real figure, no inflation. What matters more to me is the role and the runway, but you should have an accurate picture.",
          points: 6,
          standing: 11,
          momentum: 15,
          reaction: "Thank you for not playing games with the number. That makes it far easier for me to fight for you.",
          principle: "Give an accurate figure so your credibility carries the rest of the conversation.",
          keywords: ["honest number", "accurate", "no inflation", "credibility", "transparent", "precise"],
        },
        {
          id: "s2-bluff",
          tag: "Bluff a higher number",
          line: "It is well into the top of the band, higher than anything we pay here, so you will really need to stretch to stay close.",
          points: -3,
          standing: -15,
          momentum: -5,
          reaction: "Funny. We know what that company pays. If your number does not survive a phone call, neither does your story.",
          principle: "Bluffing a figure that can be checked destroys the trust your whole case depends on.",
          keywords: ["bluff", "inflate number", "exaggerate", "dishonest", "false figure", "risk"],
        },
        {
          id: "s2-package",
          tag: "Redirect to the whole package",
          line: "The cash is one line. What I am really weighing is scope, the team, and the title. Let me walk you through the full shape of it.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Good, because we are never going to win on cash alone. Talk to me about scope.",
          principle: "Shift from a single number to the full package so the contest moves to ground you can win on.",
          keywords: ["whole package", "scope", "title", "team", "redirect", "value"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Give me something I can actually work with here.",
        principle: "Be the most reliable narrator in the room and your numbers stop being questioned.",
      },
    },
    {
      id: "s3-doubt",
      prompt: "She studies you. \"Honestly, part of me wonders if you already have one foot out the door and this is just theater.\"",
      choices: [
        {
          id: "s3-onefoot",
          tag: "Sound half-gone",
          line: "I will be honest, I am pretty checked out already. If this does not move I am probably gone regardless of what we say today.",
          points: -2,
          standing: -13,
          momentum: -4,
          reaction: "Then why would I spend capital upstairs on someone who has already left in their head? You just told me not to bother.",
          principle: "Signaling that you have mentally left removes the reason for anyone to invest in keeping you.",
          keywords: ["checked out", "half gone", "disengaged", "one foot out", "indifferent", "withdraw"],
        },
        {
          id: "s3-commit",
          tag: "Show genuine commitment",
          line: "It is the opposite. I am here precisely because I am committed. I would not spend this energy on a place I had already left.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "That lands. People who are leaving do not push this hard for a better path to stay. Okay, I believe you.",
          principle: "Demonstrate that the effort itself is proof of commitment, not a sign of departure.",
          keywords: ["commitment", "invested", "here to stay", "effort", "loyalty", "genuine"],
        },
        {
          id: "s3-evidence",
          tag: "Point to recent work",
          line: "Look at what I have shipped this quarter. That is not the output of someone with a foot out the door, that is someone betting on this place.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Fair. The work speaks for itself, and it does not look like someone coasting toward an exit.",
          principle: "Let visible, recent results answer doubts about your commitment more credibly than reassurance does.",
          keywords: ["evidence", "recent work", "track record", "results", "proof", "delivery"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Convince me you actually want to be here.",
        principle: "When loyalty is questioned, point to behavior, because behavior is harder to fake than words.",
      },
    },
    {
      id: "s4-close",
      prompt: "She picks up her pen. \"Alright. I am willing to push. Tell me exactly what you want me to bring upstairs.\"",
      choices: [
        {
          id: "s4-path",
          tag: "Ask for a concrete accelerated path",
          line: "Bring them a clear path to VP on a named timeline, with the scope spelled out. Give me a defined milestone and a date, and I will recommit on the spot.",
          points: 6,
          standing: 11,
          momentum: 17,
          reaction: "That I can sell. A real path with a date is something leadership can say yes to. Let me go get it.",
          principle: "Close by asking for a specific path with a named milestone and date, not a vague promise.",
          keywords: ["accelerated path", "named timeline", "milestone", "concrete ask", "recommit", "specific"],
        },
        {
          id: "s4-vague",
          tag: "Ask vaguely for more",
          line: "Just get me more. More money, more title, more whatever you can pull together. I will know it when I see it.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "More of what, by when? I cannot walk upstairs and ask for more in general. You are making me do your homework.",
          principle: "A vague close forces the other side to define your ask, which weakens it and stalls the timeline.",
          keywords: ["vague ask", "more in general", "undefined", "no specifics", "loose", "stall"],
        },
        {
          id: "s4-gratitude",
          tag: "Anchor to growth and thank her",
          line: "Thank you for fighting for this. What I care about most is the growth and the scope, so anchor it there and the rest follows.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Growth and scope, noted. That is the version of this story that wins upstairs anyway.",
          principle: "Keep the final ask centered on growth so the deal reads as ambition rather than extraction.",
          keywords: ["growth", "scope", "gratitude", "anchor", "ambition", "not money"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Give me the specific thing to carry upstairs.",
        principle: "A request only accelerates a timeline when it names the milestone and the date.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 50 },
      result: "won",
      baseGrade: "A",
      resolution: "You used the offer as a clean signal of market value and never once reached for the threat. By the time you closed, you had asked for a defined path to VP with a named milestone and date, and your decision partner left the room ready to sell exactly that upstairs. You accelerated the timeline and walked out with your trust capital fully intact.",
      lessons: [
        "Lead with your preference to stay so an outside offer reads as information, not an ultimatum.",
        "Keep the contest on scope and growth, the ground you can win on, rather than a single number.",
        "Close by asking for a specific path with a named milestone and date, not a vague promise of more.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You kept the conversation civil and got her willing to advocate, but you left some doubt on the table about your commitment or let the ask stay loose. She will carry something upstairs, though it is softer and slower than what you could have secured. You protected the relationship but did not fully convert it into an accelerated, dated path.",
      lessons: [
        "Goodwill without a concrete, dated ask tends to stall before it reaches a decision.",
        "Answer doubts about your commitment with behavior and results, not just reassurance.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "Either you turned the offer into an ultimatum, bluffed a number that did not survive scrutiny, or signaled that you had already left in your head. Whatever the path, you spent your trust instead of your value, and your decision partner has no reason to fight for someone who threatened her or already checked out. The timeline did not move and the relationship took the damage.",
      lessons: [
        "An ultimatum converts a value conversation into a power test you usually lose internally.",
        "Bluffing a checkable number destroys the credibility your whole case rests on.",
        "Signaling that you are already gone removes any reason for anyone to invest in keeping you.",
      ],
    },
  ],
};
