import type { Encounter } from "../../game/types";

export const peerTurf: Encounter = {
  id: "peer-turf",
  title: "The Land Grab",
  opponent: {
    name: "The Counterpart",
    role: "A territorial peer who thinks you are encroaching",
    archetype: "Territorial Counterpart",
    blurb: "He is spinning a land-grab narrative about you. De-escalate and split the turf cleanly.",
  },
  difficulty: "pointed",
  scene: "A peer is spreading a narrative that you are grabbing his territory. You need to de-escalate and propose a clean governance split.",
  objective: "Defuse the land-grab story and land a governance split that both of you can sell.",
  startStanding: 40,
  startMomentum: 20,
  stages: [
    {
      id: "s1-open",
      prompt: "He shuts your door. \"People are telling me you are quietly taking over my function. So let us be adults. What exactly are you trying to pull?\"",
      choices: [
        {
          id: "s1-attack",
          tag: "Defend by attacking",
          line: "I am not pulling anything. Maybe if your team were actually covering this, I would not have had to step in. This is on you.",
          points: -3,
          standing: -12,
          momentum: -5,
          reaction: "So now it is my fault you are in my lane. That is exactly the arrogance I have been warning people about.",
          principle: "Counter-attacking when accused of a land grab confirms the very narrative you need to kill.",
          keywords: ["attack back", "blame him", "your fault", "defensive aggression", "escalate"],
        },
        {
          id: "s1-sharedgoal",
          tag: "Name the shared goal",
          line: "Before we get into lanes, we both want the same thing here, which is this product not falling between us. I would rather fix that with you than become each other's problem.",
          points: 5,
          standing: 9,
          momentum: 14,
          reaction: "All right. Yes, I do want the product covered. If that is where you are starting, I am willing to hear you out.",
          principle: "Open a turf conflict by naming the shared goal so the other person stops seeing you as the threat.",
          keywords: ["shared goal", "common ground", "same outcome", "de-escalate", "we both want", "lower temperature"],
        },
        {
          id: "s1-listen",
          tag: "Ask what he is hearing",
          line: "I clearly stepped on something. Tell me exactly what people are saying, because I would rather hear it straight from you than secondhand.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Fine. What I am hearing is that you are making decisions on my turf without a word to me. That is the problem.",
          principle: "Asking to hear the accusation directly defuses gossip and shows you are not hiding from it.",
          keywords: ["ask what he hears", "listen", "hear it straight", "surface the rumor", "no defensiveness"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "I am still deciding if you are a problem or not.",
        principle: "Lower the temperature before you touch the substance.",
      },
    },
    {
      id: "s2-overlap",
      prompt: "He crosses his arms. \"Do not insult me by pretending there is no overlap. We both know your team has been making calls on my accounts.\"",
      choices: [
        {
          id: "s2-deny",
          tag: "Deny the overlap",
          line: "I think you are imagining the overlap. There really is not any, and the accounts you mean were never clearly yours.",
          points: -3,
          standing: -11,
          momentum: -5,
          reaction: "Imagining it? I have the emails. Now you are gaslighting me, and that ends any goodwill I had.",
          principle: "Denying an overlap the other side can prove turns a fixable dispute into a credibility war.",
          keywords: ["deny overlap", "gaslight", "pretend no problem", "dishonest", "lose trust"],
        },
        {
          id: "s2-admit",
          tag: "Admit it plainly",
          line: "You are right, there is overlap, and some of those calls should have come through you. I am not going to pretend otherwise. That is exactly what I want to fix.",
          points: 5,
          standing: 9,
          momentum: 13,
          reaction: "Okay. That is the first honest thing anyone has said about this. Now I am actually listening.",
          principle: "Admitting the overlap plainly removes the fight and frees both of you to solve it.",
          keywords: ["admit overlap", "you are right", "honesty", "own it", "no pretending", "defuse"],
        },
        {
          id: "s2-minimize",
          tag: "Acknowledge but minimize",
          line: "There is a little overlap, sure, but it is smaller than it has been made to sound.",
          points: 1,
          standing: 2,
          momentum: 4,
          reaction: "A little. We will see about that. At least you are not denying it outright.",
          principle: "Minimizing a real overlap concedes the point but keeps a thread of distrust alive.",
          keywords: ["minimize", "downplay", "a little overlap", "half admit", "hedge"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Just be straight with me about what happened.",
        principle: "Concede the visible facts so the conversation can move to the fix.",
      },
    },
    {
      id: "s3-split",
      prompt: "He softens slightly. \"Say I believe you want to fix it. How? Because I am not handing anything over on a handshake.\"",
      choices: [
        {
          id: "s3-escalate",
          tag: "Escalate to the bosses",
          line: "Let us just take it upstairs and have our VPs draw the line for us. They can settle it.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "Run to our bosses so they see two peers who cannot sort out their own turf? No thanks. That makes us both look weak.",
          principle: "Escalating a peer dispute to leadership signals neither of you can be trusted to govern your own scope.",
          keywords: ["escalate", "go to bosses", "involve vps", "cannot self govern", "look weak"],
        },
        {
          id: "s3-cleansplit",
          tag: "Propose a clear ownership split",
          line: "Here is a clean line. You own the named accounts and all renewals. I own net-new in the adjacent segment. Anything in the gray zone, we flag to each other before we act. Written down, so there is no handshake risk.",
          points: 5,
          standing: 9,
          momentum: 14,
          reaction: "That is actually clear. You keep your lane, I keep mine, and the gray stuff gets flagged. I can work with that.",
          principle: "Resolve turf by proposing a specific, written ownership line with a rule for the gray zone.",
          keywords: ["clear split", "ownership line", "written", "gray zone rule", "governance", "specific boundary"],
        },
        {
          id: "s3-loose",
          tag: "Suggest staying flexible",
          line: "Let us just keep it loose and coordinate as we go. We are both reasonable, we can feel it out.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Loose is how we got here. But I will take coordination over a turf war, for now.",
          principle: "A loose arrangement avoids conflict today but leaves the next overlap unsettled.",
          keywords: ["stay flexible", "keep it loose", "coordinate", "no firm line", "avoid specifics"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Show me a line I can actually hold you to.",
        principle: "Offer a concrete boundary, not a vibe.",
      },
    },
    {
      id: "s4-close",
      prompt: "He nods slowly. \"This could work. But I have spent two weeks telling people you were grabbing my turf. How do I walk that back without looking like a fool?\"",
      choices: [
        {
          id: "s4-win",
          tag: "Give him a visible win",
          line: "Easy. We announce it as your idea. You drove the alignment, you protected the accounts, you set the governance. I will say it in the room with our boss watching. You come out of this looking like the one who fixed it.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "You are handing me the credit for this. Done. Send me the split and I will take it to the team as ours.",
          principle: "Let the other person claim the public win so they have a reason to sell the deal instead of resenting it.",
          keywords: ["give him credit", "visible win", "his idea", "save face", "public credit", "let him sell it"],
        },
        {
          id: "s4-claim",
          tag: "Take the credit yourself",
          line: "I will let people know I came in and sorted this out. The narrative corrects itself once they see I resolved it.",
          points: -3,
          standing: -13,
          momentum: -5,
          reaction: "So you grab my accounts and then grab the credit for being the peacemaker too. Forget it. The deal is off.",
          principle: "Taking the credit for resolving a turf fight you were blamed for restarts the war.",
          keywords: ["take credit", "i sorted it", "peacemaker for self", "grab the win", "humiliate peer"],
        },
        {
          id: "s4-quiet",
          tag: "Keep it quiet",
          line: "Let us just not make a thing of it. We quietly run the new split and let the noise die down on its own.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Quiet works, I suppose. Though I would rather have something to point to than just hope it fades.",
          principle: "Letting a dispute fade quietly is safe but leaves your peer without a story to tell.",
          keywords: ["keep quiet", "let it fade", "no announcement", "low profile", "no face saver"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Give me a way to come out of this without losing face.",
        principle: "Hand your counterpart a story they can tell to save face.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 40 },
      result: "won",
      baseGrade: "A",
      resolution: "You killed the land-grab narrative by naming the shared goal, admitting the overlap plainly, and proposing a clean written split with a rule for the gray zone. Then you handed him the public credit so he had every reason to sell the deal as his own. He walked out an ally instead of an enemy, and both of you can defend the boundary to your teams.",
      lessons: [
        "Open a turf conflict by naming the shared goal so you stop being seen as the threat.",
        "Admit a provable overlap plainly so the conversation can move from fight to fix.",
        "Let your counterpart claim the public win so they sell the deal instead of resenting it.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You took the heat out of the situation and avoided open war, but you left the resolution loose or quiet. The two of you have an understanding rather than a clean, defensible split, and your peer has no clear story to tell his team. The next overlap will likely reopen the question.",
      lessons: [
        "De-escalation without a concrete boundary just postpones the next collision.",
        "A peer who cannot point to a visible outcome stays quietly uneasy about the deal.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "You made it worse. Whether you attacked back, denied an overlap he could prove, ran to the bosses, or grabbed the credit for fixing it, you confirmed the land-grab story and hardened him against you. He is now a committed adversary spreading a narrative that has your fingerprints all over it.",
      lessons: [
        "Counter-attacking or denying a provable overlap confirms the exact narrative you need to kill.",
        "Escalating a peer dispute to leadership makes you both look unable to govern your own scope.",
        "Grabbing the credit for resolving a fight you were blamed for restarts the war.",
      ],
    },
  ],
};
