import type { Encounter } from "../../game/types";

export const principalPromo: Encounter = {
  id: "principal-promo",
  title: "The VP Case",
  opponent: {
    name: "The Principal",
    role: "The decision maker poking holes in your numbers",
    archetype: "Skeptical Principal",
    blurb: "He makes the VP call and he is hostile to your figures. Hold the case.",
  },
  difficulty: "adversarial",
  scene: "You make the direct VP case to the decision maker while he aggressively pokes holes in your numbers.",
  objective: "Hold your VP case under attack by owning the gaps and reframing scope without inflating.",
  startStanding: 35,
  startMomentum: 15,
  stages: [
    {
      id: "s1-open",
      prompt: "He does not look up. \"You want VP. I have seen your deck. Half these numbers are generous and you know it. Why are you wasting my morning?\"",
      choices: [
        {
          id: "s1-own",
          tag: "Own the weak spot first",
          line: "You are right about one of them. The pipeline figure is optimistic, and I should have flagged it. Here is the conservative version, and the case still stands.",
          points: 6,
          standing: 9,
          momentum: 14,
          reaction: "Huh. You walked into your own weak number before I had to drag it out. Keep talking.",
          principle: "Owning your weakest figure first disarms the attack and buys credibility for everything else.",
          keywords: ["own the gap", "concede weak spot", "honesty first", "conservative version", "disarm", "credibility"],
        },
        {
          id: "s1-bluff",
          tag: "Bluff the number",
          line: "Every figure in there is solid and stress tested. There is nothing generous about any of it.",
          points: -3,
          standing: -14,
          momentum: -6,
          reaction: "Nothing generous? I can name three on this page. So either you cannot see it or you are lying to me. Neither helps you.",
          principle: "Defending a number you know is soft hands the room to the person attacking it.",
          keywords: ["bluff", "defend everything", "deny weakness", "overclaim", "stonewall"],
        },
        {
          id: "s1-narrow",
          tag: "Narrow to your strongest point",
          line: "Set the deck aside for a second. The one thing that is not in dispute is what I shipped last year. Let me build from there.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Fine. Start from what you actually did. That is firmer ground than your projections.",
          principle: "When numbers are under fire, retreat to the undisputed facts and rebuild from solid ground.",
          keywords: ["narrow", "strongest point", "shipped", "undisputed", "solid ground", "track record"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 2,
        reaction: "Get to the part I can actually verify.",
        principle: "Under attack, lead with what is true and undeniable.",
      },
    },
    {
      id: "s2-attack",
      prompt: "He jabs a finger at the slide. \"This impact number. You are taking credit for a team result. That is not a VP, that is someone good at framing.\"",
      choices: [
        {
          id: "s2-credit",
          tag: "Claim it all anyway",
          line: "No, that was driven by me. The team executed, but the result is mine and I stand behind the full number.",
          points: -3,
          standing: -13,
          momentum: -6,
          reaction: "So you grab the whole thing and shove your team under the bus in the same breath. That is the opposite of VP.",
          principle: "Overclaiming credit under fire signals exactly the lack of judgment a VP role cannot have.",
          keywords: ["claim all credit", "grab credit", "throw team under bus", "overclaim", "no judgment"],
        },
        {
          id: "s2-judgment",
          tag: "Reframe to your judgment",
          line: "The team delivered, and I will not pretend otherwise. What is mine is the call to bet on that problem when nobody else would. That judgment is what you are actually evaluating.",
          points: 6,
          standing: 10,
          momentum: 15,
          reaction: "All right. The bet was yours, the execution was theirs. That is a cleaner story and it is the part I care about.",
          principle: "Reframe from raw output to the judgment call you owned, which is what a senior role is really tested on.",
          keywords: ["reframe to judgment", "credit the team", "i made the call", "the bet", "what is mine", "scope"],
        },
        {
          id: "s2-split",
          tag: "Split it honestly",
          line: "Fair. Call it shared. My piece was the strategy and the unblocking. I can break down exactly which parts were mine.",
          points: 2,
          standing: 4,
          momentum: 5,
          reaction: "Shared is more honest than what is on the slide. Show me the breakdown.",
          principle: "Honestly splitting credit costs you nothing and proves you can be trusted with attribution.",
          keywords: ["split credit", "shared", "honest attribution", "my piece", "breakdown"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 2,
        reaction: "Tell me what was actually yours.",
        principle: "Separate your judgment from the team's execution and own only your part.",
      },
    },
    {
      id: "s3-trap",
      prompt: "He sits back, testing you. \"Convince me someone above me thinks you are ready. Who is in your corner?\"",
      choices: [
        {
          id: "s3-namedrop",
          tag: "Name-drop a senior backer",
          line: "The COO and two of the SVPs are firmly behind me. They will tell you the same. You can ask them.",
          points: -3,
          standing: -12,
          momentum: -6,
          reaction: "So your case rests on names you want me to be afraid of. If you need them in the room, you are not ready for the room.",
          principle: "Name-dropping to a decision maker reads as a threat and admits your case cannot stand alone.",
          keywords: ["name drop", "senior backer", "drop names", "borrow authority", "intimidate"],
        },
        {
          id: "s3-outcomes",
          tag: "Let outcomes answer it",
          line: "I would rather not lean on names. Look at what the last two bets returned and whether the org trusts me with bigger ones. That answer is more useful than a list of sponsors.",
          points: 6,
          standing: 9,
          momentum: 14,
          reaction: "Good. You did not hide behind anyone. The outcomes do talk, and they are not bad.",
          principle: "Let your results carry the argument instead of borrowing authority from senior names.",
          keywords: ["cite outcomes", "results speak", "decline name drop", "track record", "stand alone", "calm"],
        },
        {
          id: "s3-honest",
          tag: "Admit support is still building",
          line: "Honestly, the support is real but still building. I would rather tell you that straight than oversell a coalition I do not fully have yet.",
          points: 3,
          standing: 4,
          momentum: 6,
          reaction: "Telling me it is half built instead of pretending. That actually moves you up in my book.",
          principle: "Admitting where your support is thin reads as confidence, not weakness, to a skeptic.",
          keywords: ["honest about support", "still building", "no oversell", "candor", "straight answer"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 2,
        reaction: "I asked who backs you, not who you can quote.",
        principle: "Carry your own case rather than borrowing senior names.",
      },
    },
    {
      id: "s4-close",
      prompt: "He folds his arms. \"Last shot. Tell me why I should put your name forward this cycle and not next.\"",
      choices: [
        {
          id: "s4-scope",
          tag: "Close on scope and proof",
          line: "Because I am already doing the VP scope without the title. The conservative numbers hold, I owned the gaps you found, and I will run the next bet under whatever scrutiny you want. Putting my name forward costs you nothing if I am wrong, and you have the proof if I am right.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "You held the case the whole way without inflating once. I will put your name forward. Do not make me regret it.",
          principle: "Close by showing you already operate at the level, with the gaps owned and the proof on the table.",
          keywords: ["already doing the scope", "owned the gaps", "proof", "no inflation", "calm close", "ready now"],
        },
        {
          id: "s4-pressure",
          tag: "Threaten to walk",
          line: "Because if it is not this cycle, I will start taking calls from people who see it. I would rather not, but I will.",
          points: -2,
          standing: -11,
          momentum: -5,
          reaction: "Threatening to leave to get promoted. That is a pressure play, not readiness, and it makes the no easy.",
          principle: "Ultimatums under evaluation convert a maybe into a no by replacing your case with a threat.",
          keywords: ["threaten to walk", "ultimatum", "take other calls", "pressure tactic", "force the hand"],
        },
        {
          id: "s4-modest",
          tag: "Defer to his timing",
          line: "If you think next cycle is cleaner, I will take that. I just want to be in the conversation.",
          points: 1,
          standing: 2,
          momentum: 4,
          reaction: "At least you are not forcing it. But I needed you to tell me why now, and you blinked.",
          principle: "Deferring at the close when you have the case wastes the moment to make the now argument.",
          keywords: ["defer", "his timing", "blink", "no conviction", "give up the ask"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 2,
        reaction: "Give me the now argument, plainly.",
        principle: "Make the case that you already operate at the level you are asking for.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 35 },
      result: "won",
      baseGrade: "A",
      resolution: "You held the case through every jab. You conceded the soft number before he could swing it, split credit honestly, let your outcomes answer for your readiness, and closed by showing you already carry the scope. He agreed to put your name forward this cycle. You won not by having a perfect deck, but by being the calmest, most honest person in a hostile room.",
      lessons: [
        "Own your weakest number first to disarm the attack and earn credibility for the rest.",
        "Reframe from raw output to the judgment calls you owned, which is what senior roles are tested on.",
        "Let your outcomes carry the argument rather than borrowing authority from senior names.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You survived the room without collapsing, and he did not dismiss you. But a moment of defensiveness or a blink at the close left him unconvinced about this cycle. He will likely flag you as a strong candidate for next time rather than putting your name forward now.",
      lessons: [
        "Honesty about thin support reads as confidence, but you still have to make the now argument.",
        "Holding the case is not enough if you give up the timing the moment he pushes.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "He found the cracks and you widened them. Whether you bluffed a number, grabbed credit, leaned on senior names, or threatened to walk, you handed him every reason to pass. The case fell apart under pressure, which is exactly what he was testing for. Your name does not go forward.",
      lessons: [
        "Defending a number you know is soft hands the room to whoever is attacking it.",
        "Name-dropping and ultimatums read as threats and make the no easy.",
        "Overclaiming credit under fire signals the very lack of judgment a senior role cannot afford.",
      ],
    },
  ],
};
