import type { Encounter } from "../../game/types";

export const principalBudget: Encounter = {
  id: "principal-budget",
  title: "The Budget Defense",
  opponent: {
    name: "The Principal",
    role: "A skeptical principal stakeholder holding the purse",
    archetype: "Skeptical Principal",
    blurb: "She questions every dollar. Defend your headcount ask without overreaching.",
  },
  difficulty: "pointed",
  scene: "You are defending a headcount or budget ask under hard questioning from a principal who distrusts inflated requests.",
  objective: "Win the ask by tying it to a concrete outcome and keeping the request proportionate.",
  startStanding: 40,
  startMomentum: 20,
  stages: [
    {
      id: "s1-frame",
      prompt: "She slides your request across the table. \"Three more heads. Everyone wants more heads. Convince me this is not just empire building.\"",
      choices: [
        {
          id: "s1-outcome",
          tag: "Tie it to one outcome",
          line: "This is not about size, it is about one number. These three heads clear the renewal backlog that is costing us churn each quarter. That is the only reason I am here.",
          points: 5,
          standing: 9,
          momentum: 14,
          reaction: "Now you are speaking my language. Tie spend to churn and I will at least keep listening.",
          principle: "Anchor every ask to a single concrete outcome the decision maker already cares about.",
          keywords: ["tie to outcome", "specific number", "churn", "backlog", "business result", "anchor"],
        },
        {
          id: "s1-inflate",
          tag: "Inflate to leave room to cut",
          line: "Honestly I could use five, but I am only asking for three because I know you will want to trim something.",
          points: -3,
          standing: -11,
          momentum: -5,
          reaction: "So you padded the number expecting me to cut it. That tells me I cannot trust any figure you bring me.",
          principle: "Padding a request to absorb cuts destroys your credibility the moment it is noticed.",
          keywords: ["inflate", "pad the ask", "room to cut", "negotiation trick", "overreach"],
        },
        {
          id: "s1-team",
          tag: "Cite the team's strain",
          line: "The team is stretched thin and morale is suffering. We need the help to keep people from burning out.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "I hear that a lot. Strain is real, but it does not write me a business case on its own.",
          principle: "Strain is a valid signal but only persuades when it is attached to a measurable cost.",
          keywords: ["team strain", "morale", "burnout", "stretched thin", "soft case"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Keep going, but I need this tied to something I can measure.",
        principle: "Lead with the outcome, not the headcount.",
      },
    },
    {
      id: "s2-roi",
      prompt: "She taps the page. \"You say it pays for itself. Walk me through the return, and do not hand me a hand-wave.\"",
      choices: [
        {
          id: "s2-vague",
          tag: "Claim a big vague ROI",
          line: "The return is huge. We are talking massive efficiency gains across the whole org, easily multiples of the cost.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "Huge. Massive. Multiples. Those are words, not numbers. You just confirmed my worry.",
          principle: "Grand unquantified ROI claims read as evasion to anyone who controls a budget.",
          keywords: ["vague roi", "hand wave", "massive gains", "no numbers", "exaggeration"],
        },
        {
          id: "s2-concrete",
          tag: "Show the math conservatively",
          line: "The backlog costs us roughly two points of renewal each quarter. Three people clear it in two quarters. I have used the low end of every assumption, so the case holds even if I am wrong.",
          points: 5,
          standing: 9,
          momentum: 14,
          reaction: "You ran it on the low end. That is the first ROI in weeks I actually believe.",
          principle: "Use conservative assumptions so the case survives scrutiny instead of collapsing under it.",
          keywords: ["show the math", "conservative", "low end", "renewal points", "defensible numbers", "concrete roi"],
        },
        {
          id: "s2-partial",
          tag: "Offer a directional estimate",
          line: "I do not have it to the dollar, but the direction is clear and the upside comfortably beats three salaries.",
          points: 2,
          standing: 3,
          momentum: 5,
          reaction: "Directional is better than nothing. Tighten it and we can talk.",
          principle: "An honest directional number beats a fake precise one, but tighten it where you can.",
          keywords: ["directional", "estimate", "honest gap", "ballpark", "upside"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Give me the math, not the adjectives.",
        principle: "Quantify the return with conservative inputs you can defend.",
      },
    },
    {
      id: "s3-pushback",
      prompt: "She leans in. \"Other teams are doing more with less. Why can your group not just absorb this?\"",
      choices: [
        {
          id: "s3-defensive",
          tag: "Get defensive",
          line: "That is not fair. My team already does more than anyone, and frankly the comparison is insulting.",
          points: -3,
          standing: -12,
          momentum: -5,
          reaction: "I ask a hard question and you take it personally. That does not make me want to fund you.",
          principle: "Treating scrutiny as an attack signals you cannot defend the ask on its merits.",
          keywords: ["defensive", "take it personally", "insulting", "thin skinned", "react badly"],
        },
        {
          id: "s3-tradeoff",
          tag: "Name the explicit tradeoff",
          line: "We can absorb it, and here is what stops if we do. The backlog stays, churn continues, and that costs more than the three heads. I am happy to make that tradeoff explicit for you.",
          points: 5,
          standing: 9,
          momentum: 13,
          reaction: "Laying out what breaks if I say no. That is exactly the honesty I want from people asking me for money.",
          principle: "Answer pushback by making the cost of inaction explicit rather than defending your effort.",
          keywords: ["tradeoff", "cost of no", "what breaks", "explicit", "calm", "cost of inaction"],
        },
        {
          id: "s3-benchmark",
          tag: "Offer a fair comparison",
          line: "Comparisons are fair, so let me give you a real one. Those teams carry a fraction of our renewal volume per head. I am happy to share the ratio.",
          points: 3,
          standing: 4,
          momentum: 6,
          reaction: "A clean ratio I can check. That is a reasonable answer.",
          principle: "Meet a comparison with a verifiable metric, not with a complaint about the comparison.",
          keywords: ["benchmark", "ratio", "fair comparison", "verifiable", "volume per head"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Stay calm and answer the actual question.",
        principle: "Respond to pushback with cost and data, never with grievance.",
      },
    },
    {
      id: "s4-close",
      prompt: "She picks up her pen. \"All right. Make your final ask. And remember I remember the number you started with.\"",
      choices: [
        {
          id: "s4-proportionate",
          tag: "Hold the proportionate ask",
          line: "Three heads, tied to clearing the renewal backlog in two quarters. I will report the churn number monthly so you can pull funding if it does not move. Same number I opened with, because it was the right one.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Same number, with a kill switch if it fails. Approved. That is how I like to spend money.",
          principle: "Close by holding a proportionate ask and offering a measurable checkpoint that lets them exit if you are wrong.",
          keywords: ["proportionate", "hold the number", "monthly metric", "kill switch", "accountability", "checkpoint"],
        },
        {
          id: "s4-grab",
          tag: "Grab more while she is warm",
          line: "Since this is going well, let me actually ask for four, and maybe a tooling budget on top.",
          points: -3,
          standing: -13,
          momentum: -5,
          reaction: "There it is. The moment I soften, the ask grows. We are back to square one.",
          principle: "Expanding the ask the instant you sense a yes confirms every fear about inflation.",
          keywords: ["grab more", "expand ask", "push luck", "inflate at close", "greedy"],
        },
        {
          id: "s4-hedge",
          tag: "Soften and ask for less",
          line: "Maybe we just start with two and revisit later, if that is easier for you.",
          points: 1,
          standing: 2,
          momentum: 4,
          reaction: "Two is safer for me, sure. But now I wonder if you even believed in three.",
          principle: "Caving on a well-justified number at the close can read as doubt in your own case.",
          keywords: ["hedge", "ask for less", "soften", "undercut yourself", "lose conviction"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Land it cleanly and give me a way to measure it.",
        principle: "Close on a proportionate ask with a built-in checkpoint.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 40 },
      result: "won",
      baseGrade: "A",
      resolution: "You held the same three heads you opened with, tied them to a churn number she cares about, ran the case on conservative assumptions, and handed her a monthly checkpoint that lets her cut funding if you are wrong. She approved on the spot. You did not just win the budget, you won it in a way that makes the next ask easier.",
      lessons: [
        "Anchor every ask to a single measurable outcome the decision maker already cares about.",
        "Run the ROI on conservative inputs so the case survives scrutiny instead of collapsing under it.",
        "Offer a checkpoint that lets the funder exit if you are wrong, which makes saying yes far easier.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "She did not reject you, but she did not fully buy in either. Your case had real substance and your numbers were directionally sound, yet a soft moment or a vague claim left her wanting more before she commits. You will likely get a smaller approval or a deferral pending tighter figures.",
      lessons: [
        "Directional honesty beats false precision, but unfinished math leaves money on the table.",
        "Conviction in a justified number matters as much as the number itself.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "You confirmed her worst assumption. Whether you padded the number, hand-waved the return, took her questions personally, or grew the ask the moment she softened, she concluded she could not trust your figures. The request was denied, and the next one will face even harder questions.",
      lessons: [
        "Padding or expanding an ask destroys credibility the instant it is noticed.",
        "Grand unquantified ROI claims read as evasion to anyone holding the purse.",
        "Treating scrutiny as an attack signals you cannot defend the ask on its merits.",
      ],
    },
  ],
};
