import type { Encounter } from "../../game/types";

export const regulatorAudit: Encounter = {
  id: "regulator-audit",
  title: "The Audit",
  difficulty: "adversarial",
  opponent: {
    name: "The Compliance Officer",
    role: "A regulator who arrived unannounced for a spot check while your team lead is traveling",
    archetype: "External Counterpart",
    blurb:
      "You have to handle the first thirty minutes alone. You cannot reach legal in time. Cooperate fully without volunteering anything that creates new liability.",
  },
  scene:
    "The compliance officer arrived without notice at 9:45 AM. Your team lead is in London and unreachable for the next two hours, and legal has not picked up. You are the senior person in the room and you have about thirty minutes before the auditor will expect to begin reviewing materials.",
  objective:
    "Cooperate fully, protect the company, and say nothing that creates new liability while legal is unavailable.",
  startStanding: 38,
  startMomentum: 18,
  stages: [
    {
      id: "s1",
      prompt:
        "We are here for a routine compliance check. I will need access to your data handling logs for the past six months.",
      choices: [
        {
          id: "s1a",
          tag: "Buy ten minutes to get legal on the phone",
          line: "Of course. I want to be transparent that I am going to loop in our legal team before we begin. That is standard protocol for all external document requests, and I want to respect that process. Can I have ten minutes to reach them.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Ten minutes. I will be waiting.",
          principle:
            "Asking for time to reach legal on any external document request is the right call, even on a routine audit. It is not obstruction, it is procedure, and framing it that way prevents the auditor from treating it as a delay tactic.",
          keywords: [
            "loop in legal",
            "standard protocol",
            "external document requests",
            "ten minutes",
            "procedure",
            "before we begin",
            "reach them",
            "transparent",
          ],
        },
        {
          id: "s1b",
          tag: "Get the right internal person first",
          line: "I will get you access. I need five minutes to reach the right person internally so I can walk you through this properly.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "Five minutes.",
          principle:
            "Buying time to reach legal or a team lead is a reasonable and defensible response. It signals process awareness without framing the delay as resistance.",
          keywords: [
            "right person",
            "internally",
            "five minutes",
            "walk you through",
            "access",
            "reach",
            "properly",
          ],
        },
        {
          id: "s1c",
          tag: "Pull up the records right now",
          line: "Absolutely, I can get those right now. Let me pull them up.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "Thank you. While we are in here, I also want to look at the access control logs from Q1.",
          principle:
            "Cooperating with a document request before legal is present sets a pattern: the auditor now knows that asking produces access. Even on a routine check, procedure protects both sides.",
          keywords: [
            "right now",
            "pull up",
            "absolutely",
            "get those",
            "immediately",
            "cooperate",
            "right away",
          ],
        },
        {
          id: "s1d",
          tag: "Require a written request before proceeding",
          line: "I do not have authorization to provide those documents without a formal written request. Can you provide one before we proceed.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "This is a regulatory audit, not a voluntary information request. Obstructing access to requested materials is itself a finding.",
          principle:
            "Demanding a written request at the start of a compliance audit reads as obstruction, not procedure. There is a meaningful difference between asking for ten minutes to reach legal and refusing to proceed at all.",
          keywords: [
            "written request",
            "authorization",
            "formal",
            "not authorized",
            "provide one",
            "require",
            "before proceeding",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need to know if you are going to cooperate or not.",
        principle:
          "State your intention to cooperate fully and name the one step you need first. Asking for time to reach legal is not a refusal, it is process. Frame it that way.",
      },
    },
    {
      id: "s2",
      prompt:
        "We do not need your legal team for a routine check. This is standard.",
      choices: [
        {
          id: "s2a",
          tag: "Hold the position as procedure, not concern",
          line: "I understand, and I want to cooperate fully. Looping in legal is not about this being unusual. It is just how we handle all external document requests. It protects the integrity of the process for both of us. I can have them on the phone in eight minutes.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Eight minutes. After that, we proceed.",
          principle:
            "When an auditor pushes back on a procedural request, reframing it as protecting the process for both parties puts you on the same side as the auditor instead of across from them. It is harder to dismiss than 'I am not comfortable.'",
          keywords: [
            "not about unusual",
            "how we handle",
            "all external requests",
            "process",
            "both of us",
            "eight minutes",
            "procedure not resistance",
            "integrity",
          ],
        },
        {
          id: "s2b",
          tag: "Confirm scope while moving toward legal",
          line: "I am not trying to slow this down. Can you confirm the scope of what you need so I can make sure the right person is on the line quickly.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "Six months of data handling logs and the access control register.",
          principle:
            "Confirming scope while moving toward legal shows you are cooperating and being efficient, not stalling. It also surfaces whether the scope has expanded beyond the initial request.",
          keywords: [
            "confirm scope",
            "right person",
            "not slow down",
            "quickly",
            "on the line",
            "make sure",
            "efficient",
          ],
        },
        {
          id: "s2c",
          tag: "Drop the legal call and provide the files",
          line: "Understood. Let me get you the files.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "Good. I will also need the incident reports from the last twelve months while we are here.",
          principle:
            "Capitulating when an auditor pushes back confirms that pressure works. It also abandons the protection that legal provides, which matters most if discrepancies surface later in the session.",
          keywords: [
            "understood",
            "get you the files",
            "capitulate",
            "drop legal",
            "give in",
            "of course",
            "abandon procedure",
          ],
        },
        {
          id: "s2d",
          tag: "Say you are not comfortable proceeding",
          line: "I am not comfortable proceeding without someone from legal on the phone. That is just my personal policy.",
          points: -2,
          standing: -7,
          momentum: -3,
          reaction: "Your personal policy is not relevant to a regulatory audit. I need cooperation, not personal preferences.",
          principle:
            "Framing a procedural step as personal discomfort invites the auditor to dismiss it as subjective. Procedure is the right framing. 'I am not comfortable' sounds personal and is easy to override.",
          keywords: [
            "not comfortable",
            "personal policy",
            "my policy",
            "personally",
            "subjective",
            "personal preference",
            "not comfortable proceeding",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need to know you are cooperating in good faith.",
        principle:
          "Hold the procedural line by framing it as protecting both sides, not as resistance. The stronger your reason sounds, the harder it is to dismiss.",
      },
    },
    {
      id: "s3",
      prompt:
        "We have found a discrepancy in your Q1 records. The retention dates do not match your stated policy.",
      choices: [
        {
          id: "s3a",
          tag: "Ask to see the specific record before you respond",
          line: "I want to make sure I understand exactly what you are seeing before I respond. Can you show me the specific record? I do not want to speak to something I have not seen.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Here. Record seven forty-two. Retention date is marked ninety days. Policy states one hundred and eighty.",
          principle:
            "Asking to see the specific record before responding is not evasion, it is accuracy. Speculating about a discrepancy you have not yet seen can create admissions that were not warranted. See it first, then speak to it.",
          keywords: [
            "show me",
            "specific record",
            "before I respond",
            "have not seen",
            "understand exactly",
            "see it first",
            "accurate",
            "not speculate",
          ],
        },
        {
          id: "s3b",
          tag: "Ask for the discrepancy described specifically",
          line: "Can you help me understand the discrepancy specifically. I want to make sure I am responding to the actual record and not a general category.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "The retention dates on three Q1 records show ninety days. Your policy states one hundred and eighty.",
          principle:
            "Asking for specifics before responding surfaces whether the discrepancy is isolated or systemic and prevents you from responding to a category that may not match the actual record.",
          keywords: [
            "specifically",
            "actual record",
            "help me understand",
            "general category",
            "specific discrepancy",
            "not a general",
            "understand first",
          ],
        },
        {
          id: "s3c",
          tag: "Offer a possible explanation",
          line: "That may have been a system error during our Q1 migration. We had some data handling issues during that transition that I believe were resolved.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "So you are aware of data handling issues in Q1. Tell me more about those issues.",
          principle:
            "Speculating about cause before you have seen the record creates new liability. The words 'migration' and 'data handling issues' have now entered the audit record without you having verified whether they are even relevant.",
          keywords: [
            "may have been",
            "system error",
            "migration",
            "data issues",
            "I believe",
            "resolved",
            "speculate",
            "explain before seeing",
          ],
        },
        {
          id: "s3d",
          tag: "Assert your records are correct",
          line: "That surprises me. Our records have been reviewed internally and I believe they are up to date and accurate.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "What you believe and what the record shows are two different things. I am showing you the record.",
          principle:
            "Asserting that your records are accurate in response to a specific discrepancy you have not yet reviewed is a statement you cannot defend. It reads as starting from denial rather than from inquiry.",
          keywords: [
            "surprises me",
            "reviewed internally",
            "believe they are",
            "accurate",
            "up to date",
            "assert",
            "deny",
            "without seeing",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need a response to the specific finding, not a general statement.",
        principle:
          "Ask to see the specific record before you say anything about it. Accuracy is not avoidance. It is the safest and most defensible response under audit conditions.",
      },
    },
    {
      id: "s4",
      prompt:
        "Are there other areas where your data handling does not match your stated policy.",
      choices: [
        {
          id: "s4a",
          tag: "State what you know and decline to speculate",
          line: "I am not aware of others. I also want to be careful not to speculate, because I have not done a full audit in the last thirty minutes. With legal on the line, I can give you a more complete and accurate answer to that question. I do not want to guess and create confusion.",
          points: 6,
          standing: 11,
          momentum: 14,
          reaction: "Get legal on the phone. We will wait.",
          principle:
            "Saying you are not aware of others is honest. Adding that you will not speculate protects you from generating a list of potential issues under pressure. The request for legal is not delay, it is accuracy.",
          keywords: [
            "not aware",
            "not speculate",
            "full audit",
            "legal on the line",
            "complete and accurate",
            "do not want to guess",
            "confusion",
            "thirty minutes",
          ],
        },
        {
          id: "s4b",
          tag: "Ask to wait for legal before answering",
          line: "That is a question I want to answer accurately. Can we wait for legal to join before I respond. I do not want to give you an incomplete answer to a compliance question.",
          points: 3,
          standing: 6,
          momentum: 8,
          reaction: "How much longer for legal.",
          principle:
            "Asking for legal before answering a broad compliance question signals that you take the question seriously enough to answer it accurately, not quickly.",
          keywords: [
            "answer accurately",
            "wait for legal",
            "before I respond",
            "incomplete answer",
            "compliance question",
            "seriously",
            "accurately",
          ],
        },
        {
          id: "s4c",
          tag: "Confirm you are fully compliant",
          line: "No, we are fully compliant across the board. This appears to be an isolated record.",
          points: -3,
          standing: -10,
          momentum: -5,
          reaction: "You just confirmed there is a discrepancy. How do you know it is isolated.",
          principle:
            "Asserting full compliance after a discrepancy has already been found is a statement you cannot substantiate. It reads as defensive and invites the auditor to test whether the assertion holds.",
          keywords: [
            "fully compliant",
            "across the board",
            "isolated record",
            "compliant",
            "no other issues",
            "assert",
            "no",
          ],
        },
        {
          id: "s4d",
          tag: "Mention other areas you are reviewing",
          line: "There may be a few areas where we are actively reviewing our practices, but nothing that rises to a policy violation that I am aware of.",
          points: -2,
          standing: -8,
          momentum: -4,
          reaction: "Tell me about those areas you are actively reviewing.",
          principle:
            "Volunteering that you are reviewing your own practices opens lines of inquiry that were not on the auditor's list. Information you offer unprompted becomes part of the audit record.",
          keywords: [
            "actively reviewing",
            "practices",
            "few areas",
            "reviewing",
            "volunteer",
            "mention",
            "rises to",
            "aware of",
          ],
        },
      ],
      freeformFallback: {
        points: 0,
        standing: -3,
        momentum: -1,
        reaction: "I need a direct answer. Are there other discrepancies.",
        principle:
          "Say what you know and stop there. Do not speculate about what you do not know. 'I am not aware of others and I will not speculate' is a complete and defensible answer.",
      },
    },
  ],
  endings: [
    {
      id: "win",
      when: { momentumAtLeast: 65, standingAtLeast: 40 },
      result: "won",
      baseGrade: "A",
      resolution:
        "Legal joins at 10:12 AM, fifteen minutes before your team lead calls in from London. The auditor stays for ninety minutes total and leaves with a dated follow-up request. The Q1 discrepancy is logged as a single record pending review. You did not create any new exposure, and the process held.",
      lessons: [
        "Getting legal on the phone before documents are produced is procedure, not obstruction. Framing it as protecting the process for both sides converts a confrontation into a shared interest.",
        "See the specific record before you respond to any finding. Speculating about a cause you have not verified creates admissions that may have nothing to do with what the auditor actually found.",
        "When asked whether there are other issues, name what you know and refuse to speculate about what you do not. Guessing under audit conditions creates new exposure.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 48 },
      result: "partial",
      baseGrade: "C",
      resolution:
        "The auditor files two follow-up requests before leaving. Legal joins fifteen minutes after the first document is produced. You cooperated fully, but a moment of capitulation or an early speculation extended the scope of what is now under review. The audit is ongoing.",
      lessons: [
        "Holding the procedural line under pressure is harder when the auditor frames it as routine. Procedure is always the right framing, regardless of what the auditor calls the visit.",
        "Speculation about cause, even plausible speculation, enters the audit record and opens new lines of inquiry. Wait to see the record before you explain it.",
        "The difference between procedure and obstruction is framing. 'It protects both of us' lands differently than 'I am not comfortable.'",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution:
        "You provided documents before legal arrived, speculated about a Q1 migration issue that is now in the record, and asserted full compliance on a question you had no basis to answer. The audit scope expanded twice during the session. The compliance officer leaves with a list of follow-up items that did not exist when she arrived.",
      lessons: [
        "Cooperating before legal arrives is not full cooperation, it is premature cooperation. The process is there to protect you in exactly the scenario where you feel most pressure to skip it.",
        "Speculating about cause before you have seen the record creates admissions. Always ask to see the specific record first, even if that means a pause.",
        "Asserting full compliance after a finding has been surfaced is a statement you cannot defend. 'Not aware of others' and 'fully compliant across the board' are different claims with different consequences.",
      ],
    },
  ],
};
