import type { Encounter } from "../../game/types";

export const sayingNo: Encounter = {
  id: "saying-no",
  title: "The Graceful No",
  opponent: {
    name: "The Principal",
    role: "A leader pushing a high-visibility but low-value request",
    archetype: "Skeptical Principal",
    blurb: "Decline a flashy but low-value ask from leadership without losing standing.",
  },
  difficulty: "pointed",
  scene: "A leader pushes a high-visibility but low-value request onto you. You must decline it without losing standing or looking uncommitted.",
  objective: "Decline the low-value request while protecting your standing and offering a better path.",
  startStanding: 48,
  startMomentum: 22,
  stages: [
    {
      id: "s1-opening",
      prompt: "She is energized. \"I want you to lead the showcase booth at the conference. Big stage, lots of eyes. This is a real opportunity for you.\"",
      choices: [
        {
          id: "s1-flatno",
          tag: "Flat no, no alternative",
          line: "No, that one is not for me. The booth is not how I want to spend my time. I will pass.",
          points: -3,
          standing: -15,
          momentum: -5,
          reaction: "That is a surprisingly flat no for something I just framed as an opportunity. Are you not interested in growing?",
          principle: "A flat no with no alternative reads as disengagement and forces the other side to defend their idea.",
          keywords: ["flat no", "no alternative", "dismissive", "disengaged", "shut down", "blunt"],
        },
        {
          id: "s1-affirm",
          tag: "Affirm the goal, then redirect",
          line: "I love that you are pushing on visibility for the team, that is the right instinct. Let me make sure we point that energy at the thing that actually moves the needle.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Okay, you have my attention. I do care about the outcome more than the booth specifically. What are you thinking?",
          principle: "Affirm the underlying goal before you redirect, so a no lands as alignment rather than refusal.",
          keywords: ["affirm goal", "redirect", "align", "shared intent", "yes and", "reframe"],
        },
        {
          id: "s1-yes",
          tag: "Say yes resentfully",
          line: "Sure, fine, I will do the booth. If it is that important to you I will find the time somehow.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "I do not want a grudging yes. If your heart is not in it, it shows, and the booth is the company's face.",
          principle: "A resentful yes commits your time and your credibility while signaling neither is freely given.",
          keywords: ["resentful yes", "grudging", "cave", "passive", "obligation", "reluctant"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Tell me where you actually stand on this.",
        principle: "Start a decline by honoring the goal behind the request, not by rejecting the request itself.",
      },
    },
    {
      id: "s2-value",
      prompt: "She pushes. \"It is high visibility. Senior people will be watching. Why would you not want that exposure right now?\"",
      choices: [
        {
          id: "s2-badmouth",
          tag: "Badmouth the idea",
          line: "Honestly the booth is a vanity exercise. Lots of show, no substance. Smart people see through that kind of thing.",
          points: -3,
          standing: -14,
          momentum: -5,
          reaction: "It is my idea you just called a vanity exercise. Even if you are half right, you have made this about me now.",
          principle: "Attacking the idea attacks the person who proposed it and turns a redirect into a conflict.",
          keywords: ["badmouth", "attack idea", "vanity", "dismiss", "insult", "criticize"],
        },
        {
          id: "s2-tradeoff",
          tag: "Make the tradeoff visible",
          line: "The exposure is real, and so is the cost. The booth would pull me off the platform launch for three weeks, and that launch is where the senior eyes actually land.",
          points: 6,
          standing: 11,
          momentum: 16,
          reaction: "When you put the launch next to the booth like that, the choice is obvious. I had not weighed the cost.",
          principle: "Make the tradeoff visible so the other person chooses to deprioritize the ask themselves.",
          keywords: ["tradeoff", "opportunity cost", "compare", "prioritize", "visible cost", "either or"],
        },
        {
          id: "s2-honest",
          tag: "Name where your value is highest",
          line: "I want exposure too. I just think I create far more of it by shipping the launch well than by standing at a booth. That is where I am strongest.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "Fair point. You probably do generate more attention by delivering than by presenting. I will grant you that.",
          principle: "Anchor your no to where you create the most value, so it reads as judgment rather than avoidance.",
          keywords: ["highest value", "strength", "judgment", "deliver", "where i shine", "honest"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Convince me this is not just you dodging the spotlight.",
        principle: "Frame a decline around value and tradeoffs, not around what you would prefer to avoid.",
      },
    },
    {
      id: "s3-alternative",
      prompt: "She softens but presses. \"Alright, but I still need the booth covered and I need it to look strong. So what do I do with it?\"",
      choices: [
        {
          id: "s3-dump",
          tag: "Dump it back on her",
          line: "That is really your problem to solve. You wanted the booth, so staffing it is on you and your team, not me.",
          points: -2,
          standing: -12,
          momentum: -4,
          reaction: "So you decline and then hand me the cleanup. That is not partnership, that is just walking away.",
          principle: "Declining without helping solve the resulting gap makes your no a cost to the other person.",
          keywords: ["dump it", "your problem", "walk away", "no help", "abandon", "offload"],
        },
        {
          id: "s3-lighter",
          tag: "Offer a lighter alternative",
          line: "Here is a better version. Let me prep the strongest person on my team to run it with my full backing, and I will record a short keynote that plays on loop. Stronger booth, and I stay on the launch.",
          points: 6,
          standing: 11,
          momentum: 17,
          reaction: "That is genuinely better than what I asked for. The booth gets covered, it looks strong, and you stay on the launch. Done.",
          principle: "Offer a lighter alternative that meets the real need, so your no comes with a better yes attached.",
          keywords: ["lighter alternative", "delegate", "better path", "solve the gap", "offer", "win win"],
        },
        {
          id: "s3-suggest",
          tag: "Point to a better owner",
          line: "Marketing is actually built for this and would kill for the stage. Let me connect you to their lead. They get the visibility, you get a stronger booth.",
          points: 3,
          standing: 5,
          momentum: 8,
          reaction: "That makes sense. They would do it better and want it more. Make the intro.",
          principle: "Routing a request to a better-suited owner turns your no into a service for everyone involved.",
          keywords: ["better owner", "route", "connect", "right fit", "delegate up", "intro"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Give me a path, not just a problem.",
        principle: "A no lands far better when it arrives holding a solution to the gap it creates.",
      },
    },
    {
      id: "s4-close",
      prompt: "She nods, mostly convinced. \"Okay. I can live with this. Just make sure I do not look like I dropped the ball by not having you front and center.\"",
      choices: [
        {
          id: "s4-cover",
          tag: "Protect her and reaffirm commitment",
          line: "You will look sharp on this. I will brief you so you can speak to the launch with real authority at the conference. We are pointed at the same win, and I have got your back.",
          points: 6,
          standing: 10,
          momentum: 17,
          reaction: "That is exactly what I needed to hear. You are not stepping back, you are stepping into the thing that matters. I am behind you.",
          principle: "Close a no by protecting the other person's standing and reaffirming your commitment to the shared goal.",
          keywords: ["protect relationship", "reaffirm commitment", "cover them", "shared win", "have your back", "loyal"],
        },
        {
          id: "s4-cold",
          tag: "End it transactionally",
          line: "Great, so we are agreed, I am off the booth. Glad that is settled. Send me anything else when you have it.",
          points: -2,
          standing: -9,
          momentum: -4,
          reaction: "We solved the logistics and you still managed to make it feel like I lost. Watch that.",
          principle: "Winning the decision but skipping the relationship leaves the other person feeling defeated.",
          keywords: ["transactional", "cold close", "all business", "no warmth", "dismissive", "win only"],
        },
        {
          id: "s4-reopen",
          tag: "Hedge and reopen the door",
          line: "Although, if you really feel strongly about it, I suppose I could find a way to do the booth too after all.",
          points: -3,
          standing: -13,
          momentum: -5,
          reaction: "Now I do not know what we decided. You argued me out of it and then offered it back. Pick a position.",
          principle: "Reopening a decision you just won squanders your credibility and undoes the clean no.",
          keywords: ["hedge", "reopen", "waffle", "undo decision", "wishy washy", "backtrack"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Just make sure we walk out of here aligned.",
        principle: "Seal a no by leaving the other person looking good and certain you are still on their side.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 48 },
      result: "won",
      baseGrade: "A",
      resolution: "You declined the booth without ever sounding like you were declining her. You affirmed her goal, made the tradeoff against the launch impossible to miss, and handed her a lighter path that covered the booth better than your own presence would have. Then you closed by protecting her standing and reaffirming the shared win. You held the line, kept your focus, and came out with more standing than you walked in with.",
      lessons: [
        "Affirm the goal behind a request before you redirect, so a no lands as alignment, not refusal.",
        "Make the tradeoff visible so the other person chooses to deprioritize the ask themselves.",
        "A no lands best when it arrives holding a better yes and protects the other person's standing.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "You got out of the booth and kept the relationship mostly intact, but you left it cooler or looser than you should have. She accepted the outcome without fully feeling like a partner in it, or you let the close go transactional. You protected your time, though not the full standing you could have walked away with.",
      lessons: [
        "Winning the decision but skipping the relationship leaves the other person feeling defeated.",
        "A clean no still needs a warm close, or the win quietly costs you standing.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "Either you shut it down flat, attacked her idea, caved resentfully, or argued your way out and then offered it back. However it went, she leaves reading you as either uncommitted, difficult, or unable to hold a position. The low-value ask either landed back on you or cost you the standing you were trying to protect. A graceful no was right there, and you missed it.",
      lessons: [
        "A flat no with no alternative reads as disengagement and forces the other side to defend their idea.",
        "Attacking the idea attacks the person who proposed it and turns a redirect into a conflict.",
        "Reopening a decision you just won squanders your credibility and undoes the clean no.",
      ],
    },
  ],
};
