import type { Encounter } from "../../game/types";

export const sponsorWindow: Encounter = {
  id: "sponsor-window",
  title: "The Sponsor's Window",
  opponent: {
    name: "The Sponsor",
    role: "Your champion, supportive but on the way out",
    archetype: "Constrained Sponsor",
    blurb: "He backs you but is leaving and spending his last capital carefully. Get one clean action before he goes.",
  },
  difficulty: "measured",
  scene: "A senior leader who rates you is leaving the company by year end. He is warm but two sided and protective of how his exit looks. You have a short window to convert his backing into a concrete action.",
  objective: "Secure one specific, low-risk sponsorship action before his window closes.",
  startStanding: 60,
  startMomentum: 22,
  stages: [
    {
      id: "s1-opening",
      prompt: "He leans back, friendly but guarded. \"You know I rate you. But it is complicated right now, with me heading out. What is on your mind?\"",
      choices: [
        {
          id: "s1-small",
          tag: "Right-size the ask",
          line: "I know your plate is delicate right now, so I am not here for anything big. One small, clean thing that costs you almost nothing.",
          points: 6,
          standing: 8,
          momentum: 14,
          reaction: "Okay. Small and clean I can work with. Tell me what it looks like.",
          principle: "Open by sizing the ask to the other person's constraints so they can say yes without exposure.",
          keywords: ["small ask", "low risk", "respect constraints", "one thing", "easy yes", "no exposure"],
        },
        {
          id: "s1-broad",
          tag: "Ask for ongoing championing",
          line: "I was hoping you would keep championing me across the leadership team on your way out, broadly, wherever it comes up.",
          points: -3,
          standing: -12,
          momentum: -5,
          reaction: "Broadly? On my way out I cannot go around campaigning for people. That is the kind of thing that follows me.",
          principle: "Vague open-ended asks read as a burden and invite a no, especially from someone protecting their exit.",
          keywords: ["ongoing support", "champion broadly", "open ended", "campaign for me", "vague request"],
        },
        {
          id: "s1-realistic",
          tag: "Ask what is realistic",
          line: "I would rather not guess at your limits. Given where you are, what could you realistically do for me in the time you have left?",
          points: 2,
          standing: 4,
          momentum: 6,
          reaction: "Fair question. There are one or two things I could probably do without making waves. Let us see if they fit.",
          principle: "When unsure of the room to ask, let the other side define the boundary, then work inside it.",
          keywords: ["ask what is possible", "let them define", "realistic", "find the boundary", "open the door"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "I am listening. Just keep in mind my situation is sensitive.",
        principle: "Read the other side's constraints before you put the ask on the table.",
      },
    },
    {
      id: "s2-optics",
      prompt: "He frowns slightly. \"Whatever I do in my last months gets read as a parting shot or a favor. I do not want my final acts to look like overreach.\"",
      choices: [
        {
          id: "s2-legacy",
          tag: "Frame it as legacy",
          line: "Then let this be part of how you are remembered. Backing the right people on your way out is not overreach, it is the cleanest legacy you can leave.",
          points: 6,
          standing: 9,
          momentum: 14,
          reaction: "I had not framed it that way. Yes. I would like the last thing I do to be putting good people in good positions.",
          principle: "Tie the ask to how the other person wants to be remembered, so helping you serves their own story.",
          keywords: ["legacy", "how you are remembered", "their story", "clean exit", "right people", "reframe"],
        },
        {
          id: "s2-mine",
          tag: "Make it about your situation",
          line: "Honestly I really need this. I have been stuck and your help is the one thing that could finally move my situation forward.",
          points: -2,
          standing: -10,
          momentum: -4,
          reaction: "I understand you need it. But I cannot spend my last credibility solving one person's problem. That is exactly the optic I am avoiding.",
          principle: "Centering your own need triggers the exact overreach fear the sponsor just named.",
          keywords: ["about me", "i need this", "my situation", "self focused", "neediness"],
        },
        {
          id: "s2-fairness",
          tag: "Appeal to fairness",
          line: "All I am asking is that the record reflect the work fairly. That is not a favor, that is just accuracy.",
          points: 2,
          standing: 3,
          momentum: 6,
          reaction: "Fairness I can stand behind. If it is just stating what is true, that is harder to attack.",
          principle: "Reframing an ask as accuracy rather than advocacy lowers the political risk for the giver.",
          keywords: ["fairness", "accuracy", "just the record", "not a favor", "defensible", "true"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Maybe. I just need to be sure it does not read as me overstepping.",
        principle: "Address the giver's fear before you press the ask, not after.",
      },
    },
    {
      id: "s3-pressure",
      prompt: "He warms up. \"You know what, I want to help. I will go to bat for you. I will lean on whoever is in your way and make some noise.\"",
      choices: [
        {
          id: "s3-fight",
          tag: "Send him to fight your manager",
          line: "That is perfect. Go after my manager directly. He has been the block, so please put real pressure on him for me.",
          points: -3,
          standing: -14,
          momentum: -5,
          reaction: "Pick a fight with your manager on my way out the door? No. That blows up on both of us and I am gone before the dust settles.",
          principle: "Never aim a departing sponsor's last capital at a direct confrontation that you will be left to absorb.",
          keywords: ["fight my manager", "go after", "confrontation", "pressure block", "escalate conflict"],
        },
        {
          id: "s3-redirect",
          tag: "Redirect to one clean action",
          line: "I appreciate the offer, but I do not need noise. I need one clean, specific thing landed with the right person. Let me make it simple for you.",
          points: 6,
          standing: 8,
          momentum: 13,
          reaction: "Good. I would rather do one thing precisely than make a lot of noise. What is the one thing?",
          principle: "Trade a generous but vague offer for a single concrete action you can actually bank.",
          keywords: ["one clean action", "specific", "decline noise", "narrow", "concrete", "make it simple"],
        },
        {
          id: "s3-narrow",
          tag: "Thank him and narrow scope",
          line: "Thank you, that means a lot. Let me take just a slice of that so it is easy on you and easy to follow through.",
          points: 3,
          standing: 4,
          momentum: 7,
          reaction: "Sure. Narrow it down for me and I will see it through.",
          principle: "Graciously shrinking a big offer makes follow-through more likely than letting it stay broad.",
          keywords: ["narrow scope", "thank you", "take a slice", "easy follow through", "shrink the ask"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Tell me precisely what you want me to do.",
        principle: "Convert a generous gesture into a defined action before it evaporates.",
      },
    },
    {
      id: "s4-close",
      prompt: "He checks his watch. \"My calendar is brutal until I leave. So. What exactly do you want from me?\"",
      choices: [
        {
          id: "s4-draft",
          tag: "Pre-write it and name who and when",
          line: "I will draft the endorsement so you barely lift a finger. You just send it to the head of the review committee by Friday. Here is exactly who and the line that matters.",
          points: 6,
          standing: 10,
          momentum: 16,
          reaction: "Done. I will read it tonight and send it Friday. That is the kind of ask I can actually finish before I go.",
          principle: "Make the yes frictionless by writing it yourself and specifying the exact recipient and date.",
          keywords: ["draft for them", "name recipient", "set deadline", "frictionless", "specific ask", "make it easy"],
        },
        {
          id: "s4-vague",
          tag: "Ask him to talk to people",
          line: "Just talk to some people for me. Put in a good word here and there wherever you can.",
          points: -2,
          standing: -9,
          momentum: -4,
          reaction: "Talk to who, about what? I do not have the runway to chase a loose request. Give me something I can actually do.",
          principle: "A loose ask at the close wastes the window you spent the whole conversation opening.",
          keywords: ["talk to people", "good word", "vague close", "loose request", "no specifics"],
        },
        {
          id: "s4-expand",
          tag: "Pile on extra favors",
          line: "And while you are at it, could you also intro me to the new VP, fix my title, and back my project budget?",
          points: -3,
          standing: -13,
          momentum: -5,
          reaction: "Now you have turned one clean favor into four. That is exactly the overreach I told you I cannot afford.",
          principle: "Greed at the finish line collapses a clean, winnable ask into an unwinnable list.",
          keywords: ["pile on", "extra favors", "overreach", "multiple asks", "greedy", "expand request"],
        },
      ],
      freeformFallback: {
        points: 1,
        standing: 1,
        momentum: 3,
        reaction: "Put it in writing and tell me the date. Then it is real.",
        principle: "A sponsorship is only banked when it has a named recipient and a deadline.",
      },
    },
  ],
  endings: [
    {
      id: "won",
      when: { momentumAtLeast: 70, standingAtLeast: 60 },
      result: "won",
      baseGrade: "A",
      resolution: "He read your draft that night and sent it to the review committee on Friday, exactly as you laid out. One clean, specific action landed before his window closed, with his name behind it and nothing left to chance. You did not just keep a champion warm, you converted his goodwill into a documented act while he still had the standing to make it count.",
      lessons: [
        "Size the ask to the giver's constraints, then make the yes frictionless with a draft, a name, and a date.",
        "Tie your ask to how the other person wants to be remembered so helping you serves their story.",
        "A favor is only real once it has a specific recipient and deadline attached.",
      ],
    },
    {
      id: "partial",
      when: { momentumAtLeast: 45 },
      result: "partial",
      baseGrade: "C",
      resolution: "He agreed in principle and meant it warmly, but you left without locking the specifics. He will probably say something nice to someone before he goes, or he might run out of runway first. You kept the relationship and the intent, but you walked away holding a promise instead of an action.",
      lessons: [
        "Goodwill that is not pinned to a concrete act tends to evaporate when the calendar gets tight.",
        "Always close a supportive conversation by naming the exact thing, the exact person, and the exact day.",
      ],
    },
    {
      id: "lost",
      when: {},
      result: "lost",
      baseGrade: "D",
      resolution: "Either you spooked him with the optics of overreach or you piled on until the clean ask became an impossible list. He hedged, made vague reassurances, and let the window close. His last capital went unspent on your behalf, and now your champion is gone.",
      lessons: [
        "A departing sponsor protects their exit above all, so never aim their last capital at a confrontation or a pile of favors.",
        "Centering your own need triggers the overreach fear and gets you a polite no.",
        "One precise, low-risk ask beats a broad one every time, especially against a closing clock.",
      ],
    },
  ],
};
